### ISSUE TITLE
headerClassName doesn't work with pivot

### ISSUE THREAD

**Issue by GuillaumeJasmin** [react-tools/react-table#1012]
`react-table@6.8.5`

When a column is used by `pivotBy` props, `headerClassName` doesn't work. It seem the column object is completely overrided when the column is a pivot, because this issue is not only for `headerClassName`, but also with custom properties.

See issue here: 
https://codesandbox.io/s/48843xw474

On this example, groups columns have the same `headerClassName`, but only the second group has the `headerClassName="backgroundRed"`. When `pivtoBy={...}` is commented, the issue disappear.

comment / uncomment the line 62 to see differences:
```js
pivotBy={["firstName", "lastName"]}
```

You wan check the console, `customProperty` and `headerClassName` are empty or undefined for the first header group

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
