### ISSUE TITLE
Feature: split .styl into layout and design

### ISSUE THREAD

**Issue by dbkaplun** [react-tools/react-table#1014]
Hello,

It would be great if react-table separated design from layout styles. In order to style the table, I have to copy [index.styl](https://github.com/react-tools/react-table/blob/master/src/index.styl), remove all the positioning (to avoid overriding), and replace all the colors. This could be improved if there was a base (layout) stylesheet and a separate stylesheet for the default theme.

Thanks for considering!

**Comment by tannerlinsley** [comment]
I welcome a PR for this. I would expect there to be three final files:
- `core.css` - the basic required styles for the table
- `theme.css` - the standard theme styles for the table
- `bundled.css` - a combination of the `core.css` and the `theme.css` files.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
