### ISSUE TITLE
Default SelectInputComponent in SelectTable renders text input field instead checkbox.

### ISSUE THREAD

**Issue by smoleniuch** [react-tools/react-table#1020]
## Is this a general question about implementation, support, api, or anything else?
Possible bug.
## What version of React-Table are you using?
6.8.6
## What bug are you experiencing, or what feature are you proposing?

This occures with `selectTable` HOC.When you omit `selectType` property it renders normal input field.
Which should not be as a default behaviour i think.

[Codesandbox](https://codesandbox.io/s/n756qw6q2m)

## What are the steps to reproduce the issue?

1.  Use `selectTable` HOC
2.  Do not specify selectType property

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
