### ISSUE TITLE
onClick in e.g. getTrProps triggers rerender of every line

### ISSUE THREAD

**Issue by ribx** [react-tools/react-table#1022]
The code in https://github.com/react-tools/react-table/blob/f55ce620411c619855a2fe2f081407e4f82727b9/src/index.js#L619-L638

result in the creation of a new object, every time the function is called. This is then the reason why every line in the table has to be rerendered when an onClick event happens, which makes the click (used to expand the line) quite unresponsive.

Did you ever think about breaking the rendering down to several components instead of methods like "makePageRow" and then use something like:

```javascript
handleOnClick = event => {
  const {onClick} = this.props
  if(onClick) {
    onClick(event)
    if(!event.preventedDefault)
      this.handleExpandClick(event)
  } else {
    this.handleExpandClick(event)
  }
}
```

If think vast parts have to be rewritten, but the performance benefits could be worth it.

Another, more dirty approach would be to use memoization:

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization
https://github.com/alexreardon/memoize-one 

What do you think?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
