### ISSUE TITLE
Fixed Header Vertical Scroll

### ISSUE THREAD

**Issue by darioM85** [react-tools/react-table#1030]
Hi i report this 

I would like to set the fixed header, I have seen the example documentation, but there is a problem with the alignment of the column headers. Looking at the css I noticed that this is solved if you add .ReactTable .rt-thead {
   overflow-y: scroll;
}

but it is not graphically "clean" to be seen because the scroll appears in the table header.
There is a way to fix this, mybe set height dinamically.
Waiting for an answer I congratulate you for the bookshop.
Thanks

**Comment by janvp** [comment]
Indeed, I'm also struggling with this. I don't know beforehand if the table body is going to overflow or not. So I also have to set

```
.rt-tbody {
  overflow-y: scroll;
}
```

otherwise, you can have the situation like in following example, when setting the pagesize on 5 rows.
https://react-table.js.org/#/story/fixed-header-w-vertical-scroll

I don't like the unnecessary scrollbars, but I don't know another solution for the moment.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
