### ISSUE TITLE
Make client implementation of toggleAll() optional in selectTable

### ISSUE THREAD

**Issue by cachvico** [react-tools/react-table#1031]
## What version of React-Table are you using?

6.5.3 and verified against latest source no obvious sbusequent changes.

## What bug are you experiencing, or what feature are you proposing?

There is no way to omit the complexity of `selectAll` by simply rendering nothing in the header row. Currently I'm using `SelectAllInputComponent: 'div',` but this generates the React warning `Unknown prop `selectType` on <div> tag...`

Suggest providing a boolean control to indicate that no toggleAll() function will be provided.

Apologies if there is a better way that already exists.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
