### ISSUE TITLE
SubComponent dependent on expander.

### ISSUE THREAD

**Issue by matiosfree** [react-tools/react-table#1032]
## What version of React-Table are you using?
react-table@6.8.6

## What feature are you proposing?
Sometimes I need to have several different expanders. For example, I have a table with languages count and users count. I want to see list of users by pressing on users count and list of languages by pressing on languages count. Here is an example: https://codesandbox.io/s/2nv5m7ko0

Now I must store this data in my own component and use:
`
expanded={this.state.expanded}
onExpandedChange={(newExpanded, index) => {....})
`

I think that it would be better to have this inside the library. You could pass expanded column name in SubComponent as the second param like
`SubComponent={(row, expandedColumn)=> {}}`
or something else to know which column was expanded.

What do you think about it?

PS. Thanks for your great library!

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
