### ISSUE TITLE
getProps throws row not defined error

### ISSUE THREAD

**Issue by rajmiglani** [react-tools/react-table#1034]
React table version @6.7.6

This issue comes only when the rows in the data are less than the pagesize in the react table. I have also tested it on the sandbox:

https://codesandbox.io/s/zw7lnqj19m

Above the data is only 5 rows and the pagesize is 10. So error occurs.

**Comment by rajmiglani** [comment]
Well I got a workaround to get rid of it eventually: 

https://codesandbox.io/s/wol7jrv30l

**Comment by matiosfree** [comment]
> Just use:
`minRows={0}`

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
