### ISSUE TITLE
Adding a className does not alter the css for SelectTableHOC

### ISSUE THREAD

**Issue by EbokianKnight** [react-tools/react-table#1036]
The className specification does not appear to work for this SelectTableHOC component. They show up in the browser class correctly, but do not correctly affect the table. See your examples for an example:
https://react-table.js.org/#/story/select-table-hoc

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
