### ISSUE TITLE
Using nested headers with Tree Table caused "TypeError: Cannot read property 'Header' of undefined"

### ISSUE THREAD

**Issue by yesharhadi** [react-tools/react-table#1037]
## Is this a general question about implementation, support, api, or anything else?

I don't believe so!

## What version of React-Table are you using?

The latest: 6.8.6.

## What bug are you experiencing, or what feature are you proposing?

When I add a nested Header for a TreeTable, I get the following error: "TypeError: Cannot read property 'Header' of undefined." To be explicit, if I change 

`{
                  Header: "First Name",
                  accessor: "first_name"
                },
                {
                  Header: "Last Name",
                  accessor: "last_name"
                }`
to

`{ Header: "Names",
              columns: [
                {
                  Header: "First Name",
                  accessor: "first_name"
                },
                {
                  Header: "Last Name",
                  accessor: "last_name"
                }
              ]
            },`

the error occurs. In a regular ReactTable, this works fine.

## What are the steps to reproduce the issue?

I provided the steps to reproduce the issue from the Tree Table demo. A simple copy+paste should do. I'm welcome to being told "you're an idiot, here's what you're doing wrong" because I'm new to React and React-Table. :)

Thank you!

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
