### ISSUE TITLE
TreeTable allows scrolling of rows with stationary Headers

### ISSUE THREAD

**Issue by yesharhadi** [react-tools/react-table#1038]
## Is this a general question about implementation, support, api, or anything else?

I don't think so.

## What version of React-Table are you using?

Latest: 6.8.6.

## What bug are you experiencing, or what feature are you proposing?

When you expand a tree all the way to the data contents, you'll be able to scroll to the left and right. You'll also notice that the Headers at the top of the table don't follow along in the scroll. I don't think this should be the default behavior or really ever allowed, since I can't see where it would be valuable.

## What are the steps to reproduce the issue?

Expand a row so that you can scroll right and left. Notice the stationary headers that don't follow the moving data.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
