### ISSUE TITLE
render boolean values by default

### ISSUE THREAD

**Issue by capaj** [react-tools/react-table#1042]
currently if I have  data like: [{a: true}, {b: false}]

when I try tot render it in a table, there's nothing in the columns. I need to write:
```js
 Cell: ({ value }) => String(value)
```

to see the values rendered. It would be nice if the table could do this for me by default. In react it doesn't make sense to return anythingelse than `jsx`, `array` or `null` from render so it should not hurt to add 

```js
if (typeof Cell(row) === boolean) {return String(Cell(row))}
```

I guess @ocalde in #799 wanted to make similar suggestion, but probably didn't have time to follow through.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by Nawazish12** [comment]
Cell: ({ value }) => String(value) 
this is working for me you just need to add this
