### ISSUE TITLE
Columns switching

### ISSUE THREAD

**Issue by nsaraf31** [react-tools/react-table#1043]
Hi

I want to use column reordering. Is it possible to click on the header and get the small list of all headers and then select a header to with we can switch.

Thanks

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
