### ISSUE TITLE
bootstrap css conflict

### ISSUE THREAD

**Issue by ngulikbae** [react-tools/react-table#1045]
hi

apply bootstrap css impact to SelectTreeTable component which rows not display

https://codesandbox.io/embed/w6xywqpyx8

![incorrect](https://user-images.githubusercontent.com/39509398/42297749-cfe45074-802b-11e8-967c-7df644485bbd.png)

kindly advice

thanks

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
