### ISSUE TITLE
Missing prop 'pages" in documentation of ReactTable props

### ISSUE THREAD

**Issue by fsarron-nexway** [react-tools/react-table#1047]
Not a bug, it's about documentation :

there is no mention of the 'pages' prop int the list of ReactTable props at https://react-table.js.org/#/story/readme

but it hopefully appears in samples as it is crucial for controlled pagination.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
