### ISSUE TITLE
Clear sorting - 3-state sorting

### ISSUE THREAD

**Issue by akiirii** [react-tools/react-table#1053]
I couldn't find answer nowhere.
It is possible in some easy way to make 3 state sorting (asc/desc/none) - I mean after 3rd click sorting is removed from that column

**Comment by Flashwit** [comment]
Hi there, I had this question as well.
I find it pretty bizarre that there is 3-state sorting...but only if you have multisort on, and you have to hold Shift to get to the unsorted state.

It would be very easy to just change up this section
```
          if (existing.desc === secondSortDirection) {
            if (additive) {
              newSorted.splice(existingIndex, 1)
            } else {
              existing.desc = firstSortDirection
              newSorted = [existing]
            }
          }
```
to remove the check for `additive` and the following `else` block.

Unfortunately to actually answer the question, I don't think there is any way around this.
I've managed to work around it because I have `manual` on all my tables and manage the table state myself. I check the difference in state and remove the entry in `sorted` if the previous state was `desc` and the next state also has a sort.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by jlhirond** [comment]
I whipped together a quick workaround for a third (none) state based on the direction provided by @Flashwit if anyone else needs it:

```
    // ReactTable props
    multiSort={false}
    sorted={this.state.sort} // this.state.sort is initially []
    onSortedChange={this.handleSortChange} />
    
    // ...
    
    handleSortChange = (newSort) => {
        // Ascending
        if (!this.state.isSorted) { // this.state.isSorted is initially false
            this.setState({
                sort: newSort,
                isSorted: true
            });
        // None
        } else if (!newSort[0].desc) {
            this.setState({
                sort: [],
                isSorted: false
            });
        // Descending
        } else {
            this.setState({ sort: newSort });
        }
    };
```
