### ISSUE TITLE
How to use getTheadThProps?

### ISSUE THREAD

**Issue by wadigzon** [react-tools/react-table#1055]
I am trying to capture the click on a column header (I believe using react-table 6.7.5)
I have this:

```
// got this from documentation
const getProps = (state, rowInfo, column, instance) => {
    return {
        onClick: (e, handleOriginal) => {
                // set loading state here
                if (handleOriginal) {
                    handleOriginal();
                }
        }
    }
}

<CheckboxTable
                manual
...
                onSortedChange={collectSortedStatus}
                getTheadThProps={getProps}
/>
```

The event gets fired just nicely, but now my collectSortedStatus callback is never called, because handleOriginal is always undefined, and there's no way to call the original handler.

I am trying to show a loading spinner right when the user clicks on the column (sorting starting), not after the icon on the column (triangle) has been updated, when you have many rows (and columns) you notice that onSortedChange gets called way after the user has clicked on the column and after the sorting icon has been updated. 

any help greatly appreciated.

**Comment by alantliang** [comment]
I am having the same issue

**Comment by wadigzon** [comment]
we moved to ag-grid not so long ago: https://www.ag-grid.com/

**Comment by tannerlinsley** [comment]
This will be easier to work around in the next version i am working on.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
