### ISSUE TITLE
How to remove empty/unused cells and shift data up (simulate rowspan)

### ISSUE THREAD

**Issue by jakub-astrahit** [react-tools/react-table#1061]
## Is this a general question about implementation, support, api, or anything else?
implementation, support

## What version of React-Table are you using?
6.8.6

## What bug are you experiencing, or what feature are you proposing?
Replace pivot cells by actual data (shift cells up).
![reacttable](https://user-images.githubusercontent.com/19378338/42890606-90a088f6-8aad-11e8-9daa-ba9b4918256e.PNG)

## Sandbox

https://codesandbox.io/s/py9m9noqkj

## What are the steps to reproduce the issue?

1. Just checkout my codesandbox link above to see what I mean.
2. I'd like to shift all rows up and remove the empty cells in the first row of the aggregation. I simply want to simulate a rowspan functionality. If there's a better solution to use rowspan, let me know. If not, how can I remove the empty cells please?

**Comment by omkar-joshi** [comment]
@tannerlinsley any update on this? I'm facing the same issue!

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
