### ISSUE TITLE
Table length on re-render

### ISSUE THREAD

**Issue by lloydamiller** [react-tools/react-table#1064]
Using React-Table to create tables of data returned from an API call. When a component re-renders after a state change with new data to create a new table, the table sometimes has the length (number of rows) from the previous rendered table. If I make the same API call a second time, the table re-renders at the correct length.

**Comment by tjgragg** [comment]
For me, table length cannot be set dynamically. Even though my component is receiving new props, with a new list, the number of rows is locked in.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by arceliver** [comment]
Just for interest, I resolved this issue setting a variable to control the exibithion of the component. I've setted on redux a loading that goes to true when action that consumes the api is called, and set it to false when the request is complete. This loading goes via props to the component that renders React Table, and control with a ternary like the following:
`{ !loading &&
          <ReactTable
            data={data}
            columns={columns}
            defaultPageSize={data.length}
            showPagination={false}
            defaultSorted={[
            {
              id: 'Id',
              desc: false,
            },
          ]}
          />
      }`

**Comment by jeppe-style** [comment]
By setting the `defaultPageSize` to a number that is larger than the expected length of data (e.g., `Number.MAX_SAFE_INTEGER`) it works for me. The additional empty rows are not displayed.

I have also set `minRows={0}`, not sure if the combination is needed.
