### ISSUE TITLE
Docs task missing CSS

### ISSUE THREAD

**Issue by lake-effect** [react-tools/react-table#1088]
## What bug are you experiencing

```
Failed to compile.

Error in ./src/App.js Module not found: ../../react-table.css in /home/user/react-table/docs/src @ ./src/App.js 24:0-32
```

## What are the steps to reproduce the issue?

1. Clone master
2. `yarn run docs`

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
