### ISSUE TITLE
Multi column Filter with dynamic data

### ISSUE THREAD

**Issue by ghost** [react-tools/react-table#1092]
## What feature are you proposing?

Is it possible can we do the multi column filter based on the dynamic table data available on one column filter.

To make it clear kindly refer this library which have that functionality.

https://github.com/cheekujha/react-table-filter

Thanks,
Gnanavel N

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
