### ISSUE TITLE
show  defaultFilter   nums>1

### ISSUE THREAD

**Issue by romy2012** [react-tools/react-table#1093]
my data

vison    nums                    time
1.7.0     200000000       2018-08-10T09:12:00
1.3.0     100000000       2018-08-10T09:12:00
1.2.0     1                       2018-08-10T09:12:00
1.1.0     1                       2018-08-10T09:12:00

I need to show  defaultFilter   nums>1,how can I do?

new data
vison    nums                    time
1.7.0     200000000       2018-08-10T09:12:00
1.3.0     100000000       2018-08-10T09:12:00

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
