### ISSUE TITLE
Editable content + sorting results in an render/update bug

### ISSUE THREAD

**Issue by jcro21** [react-tools/react-table#1096]
When modifying data in one column that will effect the sort order, the data re-sorts correctly, but the input used does not update to the new rows data.

It's simplest to reproduce here https://codesandbox.io/s/kky34kkwr

1. Enter `99` into col 2 "age", row 3
2. Press tab
3. Note the top row is now the row we edited, age=99, full=198

![image](https://user-images.githubusercontent.com/23713423/44327014-cf090e80-a4a0-11e8-85e7-251ee4499258.png)
Image above taken after entering 99 into row 3 col 2 and pressing tab.

**Comment by jcro21** [comment]
Just as a note for anyone else bumping into the same problem, I've posted a workaround on this SO https://stackoverflow.com/questions/51924985/react-table-editable-content-sorting-editable-cell-doesnt-update

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
