### ISSUE TITLE
Outdated docs for onFiltersChange

### ISSUE THREAD

**Issue by arty-name** [react-tools/react-table#1097]
The documentation for columns at https://react-table.js.org/#/story/readme mentions `onFiltersChange` callback passed to filters. Looks like this callback is not there anymore and `onChange` is passed instead.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
