### ISSUE TITLE
manual={true} and ReactTablePagination error

### ISSUE THREAD

**Issue by pinkynrg** [react-tools/react-table#1098]
## What version of React-Table are you using?
"react-table": "^6.8.6",

## What bug are you experiencing, or what feature are you proposing?

```
Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in select (created by ReactTablePagination)
    in span (created by ReactTablePagination)
    in div (created by ReactTablePagination)
    in div (created by ReactTablePagination)
    in ReactTablePagination (created by ReactTable)
    in div (created by ReactTable)
    in div (created by ReactTable)
    in ReactTable (created by HostIndex)
    in HostIndex (created by Connect(HostIndex))
    in Connect(HostIndex) (created by Route)
    in Route (created by RightColumn)
    in Switch (created by RightColumn)
    in div (created by RightColumn)
    in div (created by RightColumn)
    in RightColumn (created by _Main)
    in div (created by _Main)
    in div (created by _Main)
    in _Main (created by Connect(_Main))
    in Connect(_Main)
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
```

The above is the error I see whenever I try to use manual={true}

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
