### ISSUE TITLE
Managing the `sorted` state in a controlled component calls fetch twice

### ISSUE THREAD

**Issue by arielsvn** [react-tools/react-table#1099]
## Is this a general question about implementation, support, api, or anything else?

This is a bug report.

## What version of React-Table are you using?

6.8.6

## What bug are you experiencing, or what feature are you proposing?

Managing the `sorted` state on a controlled table calls the `fetchData` method twice.

https://codesandbox.io/s/217zyy837r

It's the same example as [React-Table - Server-side data](https://react-table.js.org/#/story/server-side-data), but I added the properties `sorted` and `onSortedChange`.

I'll keep investigating to see if I can find the issue, any help appreciated. Thanks

## What are the steps to reproduce the issue?

Open the console, and try sorting by any column. You'll see the duplicated calls to `fetchData`.

![image](https://user-images.githubusercontent.com/1882507/44607477-94fc7d00-a7be-11e8-9b36-4a0c5e4ffc3b.png)

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
