### ISSUE TITLE
Pass a function which returns a boolean to Show field instead of a boolean

### ISSUE THREAD

**Issue by alankar-anand** [react-tools/react-table#1102]
Show takes a boolean right now.

Is it possible to pass a function to Show ?

Eg: show: (d) => d.item !== null where d is the entire row data

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
