### ISSUE TITLE
Local filtering with server side rendering

### ISSUE THREAD

**Issue by vaishaliakhare** [react-tools/react-table#1103]
I am using the react-table  ^6.7.6 version. I have requirement to get the data from server but to apply filter on given page & sorting within the fetch result i.e. local sorting and filtering.
Can some one please point me to an example. I followed this example https://react-table.js.org/#/story/server-side-data as reference but no luck so far.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
