### ISSUE TITLE
Unable to filter row with inline cell editing (using an input element for cell editing)

### ISSUE THREAD

**Issue by jdpagley** [react-tools/react-table#1105]
## What version of React-Table are you using?
v6.8.6

## What bug are you experiencing, or what feature are you proposing?

I'm unable to filter the table using the built in filter or a defaultFilterMethod if the value returned from Cell renderer returns an input element that contains the cell value. I'm implementing inline editing of cells using an input element. 

I already implemented your inline example in the docs but I couldn't use a div that is editable. The editable div allows line breaks and internal html to be added, I could not have that in the application. I went with an input element because it doesn't allow any of that.

https://codesandbox.io/s/l7xjlov2j9

## What are the steps to reproduce the issue?

Using the code example above:
1. Search for roof using the working cell renderer and you'll see the proper results are returned.
2. Search for roof using the broken cell renderer (input element) and it wont return the correct results.

Thank you so much for your help. I'm a huge fan of react-table! :)

**Comment by simjoh** [comment]
It was a quite simple fix. 
by using 
```
  renderEditableCellBroken(cell) {
      return <input value={cell.value} />;
  }
```
instead of
```
  renderEditableCellBroken(cell) {
      return <input defaultValue={cell.value} />;
  }
```

defaultValue is the value the cell is set up with.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
