### ISSUE TITLE
Conditionally Hide row based on data input

### ISSUE THREAD

**Issue by rtman** [react-tools/react-table#1106]
Hi,

Is it possible to conditionally hide rows based on the data fed into react-table?

I would like to hide certain rows if the input object is like so:

```
{
    data: {...},
    show: false
}
```

Maybe there is a better way to do what I want, I'm trying not to strip out these objects I don't want the user to see. 

Thanks

(PS the link to the spectrum chat isn't working)

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
