### ISSUE TITLE
Cell renderers unnecessarily reuse or caches components.

### ISSUE THREAD

**Issue by mielecmichal** [react-tools/react-table#1107]
#### What version of React-Table are you using?
6.8.6

#### What bug are you experiencing, or what feature are you proposing?
It looks ReactTable somehow reuses Cell renderers or cache returned component. 

I have a list of objects with 2 properties each. Like: ``` [{id: "", text ""}, ...]```.
Now I would like to present input for text property. To do this I declare custom Cell renderer.
When I add correct object to list everything works fine, but when I add few objects with missing text property inputs are present but filled with last text value. It is incorrect and they should be empty in that case.

When I add key property to input component with some unique value nothing is cached.
When I recreate <ReactTable> ex. by using managed key. Duplicated inputs are also cleared.

#### Example.
https://codesandbox.io/s/r4lrwrw3jq

#### What are the steps to reproduce the issue?
1.  Click 2 times **Add correct item** (2 items are added correctly each with unique timestamp)
2.  Click **Add item with undefined text property** (1 item is added, but input is filled with last timestamp instead of empty)
3.  Click **Recreate table by changing key** (incorrectly filled inputs now are empty)

#### Notice comment in 45th line in example
When I add unique key property to Cell component it also works.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
