### ISSUE TITLE
Resizable headers causing touch issues in vertical scrolling only in iOS

### ISSUE THREAD

**Issue by ViswanathLekshmanan** [react-tools/react-table#1110]
iOS touch issue. (All browsers in iOS)

Version: 6.8.6

iOS table not scrolling vertically due to header resizable. Works fine when resizable off.

In all browsers of iPhone, react-table not vertically scrolling due to resizable header.

## What are the steps to reproduce the issue?

1.  Create a react table with 20 rows and resizable header.
2.  Columns should be 4 to 5 atleast to display horizontal scroll and resizable property
3.  Wont be able to scroll the page vertically

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
