### ISSUE TITLE
React table doesn't filter if column is hidden ("show:false")

### ISSUE THREAD

**Issue by Lolobstant** [react-tools/react-table#1111]
on react-table@6.8.6, trying to filter using the `filtered` props on a hidden column doesn't work.

exemple : https://codesandbox.io/s/93xwo98wyw

quite simply, add a filtered props for ReactTable and hide the filtered column using show:false in the column.
once hidden, react-table will show all entries.
```js
const data = [
  { elemToFilter: 1, columnTwo: "value" },
  { elemToFilter: 2, columnTwo: "value" },
  { elemToFilter: 2, columnTwo: "value" }
];
const columns = [
  { Header: "Elem to filter", id: "elemToFilter", show: false },
  { Header: "columnTwo", id: "columnTwo" }
];
const filtered = [{ id: "elemToFilter", value: 2 }];


<ReactTable data={data} columns={columns} filtered={filtered}/>
```

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by BDhara** [comment]
@tannerlinsley , can I apply the filter on a hidden column in 7.7.0? I have tried on https://codesandbox.io/s/eloquent-lichterman-prxss. Lastname column is hidden one. it doesn't show filters if the column is hidden.

**Comment by pjoulot** [comment]
Same problem here, the filter is hidden as well when a column is hidden. I am not sure how to have the column hidden but keep the filter visible and functional.
