### ISSUE TITLE
How to disable some radio buttons in SelectTable?

### ISSUE THREAD

**Issue by nick-vfip** [react-tools/react-table#1116]
## Is there a way, as i couldn't find anything on the official documentation
I am using `SelectTable` in react with `selectType='radio'`

According to my case, some of the rows should be disabled depending on the condition.

Is there a way it can be done, or the only option is to use `ReactTable` and states?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
