### ISSUE TITLE
Custom Cell components cause whole table to re-render

### ISSUE THREAD

**Issue by mike391** [react-tools/react-table#1118]
Re-opening this because it seems  like it would be beneficial to the overall performance of react-table.

Issue:
Using controlled inputs / cell components will cause the whole table to re-render on changes.

https://github.com/react-tools/react-table/issues/754

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
