### ISSUE TITLE
getTfootTdProps does not include rowInfo or column

### ISSUE THREAD

**Issue by jfbloom22** [react-tools/react-table#1120]
I am using react-table 6.7.12.   When I use getTfootTdProps, it is not providing the `rowInfo` or `column` props.  This is making it impossible for me to style the cell.   I believe the root of the issue is line 731 in index.js:
```
      const tFootTdProps = _.splitProps(getTfootTdProps(finalState, undefined, undefined, this))
```

Should the second param be the rowInfo and the 3rd the column?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
