### ISSUE TITLE
Footer sum should be changed on page change on sorting, how can i achive that.

### ISSUE THREAD

**Issue by sridummy** [react-tools/react-table#1122]
## Is this a general question about implementation, support, api, or anything else?

STOP WHERE YOU ARE and visit https://spectrum.chat/react-table. Your question has likely already been discussed there. If it hasn't, then please post it there. Github issues are no place for the mundane question. They are to be used only for bug tracking.

If you believe you have indeed uncovered a bug, then please proceed!

## What version of React-Table are you using?

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?

Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?

1.  list the steps
2.  to reproduce
3.  the issue

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
