### ISSUE TITLE
Get the information if the row is hovered

### ISSUE THREAD

**Issue by nicolasletoublon** [react-tools/react-table#1126]
So the idea would be to have the information in the cell and/or row if the current row is hovered or not. Today the only solutions I found are playing with css classes and display to show or not buttons etc. 
I have the case where I want to display a component that would have a specific behavior if the row is hovered or not. 

For now the proper solution we found is to implement a mouseEnter and set the state with the index hovered. But doing that, for some reason forces the entire table to re-render which makes it super slow. 

If you have encountered the case or have a solution please that would be nice :)

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
