### ISSUE TITLE
Undocumented property in example

### ISSUE THREAD

**Issue by makeitraina** [react-tools/react-table#1130]
Can anyone clarify and help me understand how the children property is used in the example below?

https://github.com/react-tools/react-table/blob/f55ce620411c619855a2fe2f081407e4f82727b9/docs/src/examples/utils.js#L32

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
