### ISSUE TITLE
Column show undefined bug

### ISSUE THREAD

**Issue by gutenye** [react-tools/react-table#1131]
## Is this a general question about implementation, support, api, or anything else?

STOP WHERE YOU ARE and visit https://spectrum.chat/react-table. Your question has likely already been discussed there. If it hasn't, then please post it there. Github issues are no place for the mundane question. They are to be used only for bug tracking.

If you believe you have indeed uncovered a bug, then please proceed!

## What version of React-Table are you using?

6.8.6

## What bug are you experiencing, or what feature are you proposing?

![screen_shot_2018-09-20_at_12_08_54_pm](https://user-images.githubusercontent.com/377544/45795477-7a8ac600-bcce-11e8-9ed5-e867fb839de1.jpg)

Use `show: undefined` in column, only header hides.
Use `show: false`, works fine

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

https://codesandbox.io/s/n7y8lq20vm

## What are the steps to reproduce the issue?

1. change `show: undefined` to `show: false`.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
