### ISSUE TITLE
TdComponent  - style priority is not correct

### ISSUE THREAD

**Issue by serhiiZv** [react-tools/react-table#1140]
Styles for the column will replace the styles for the tdProps
can you check the original code below ?
684 line on index.js
`
      const styles = {
        ...tdProps.style,
        ...column.style,
        ...columnProps.style,
      }
`
I think that priority should be the reverse. 
For example, I want the column to be `backgroundColor: gray` 
and for example one of the td was of a different color `backgroundColor: yellow`

In the current version I will only see `backgroundColor: gray` 
because the priority of the column style is higher than priority of the TD style

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
