### ISSUE TITLE
Tree table example filters rendering incorrectly

### ISSUE THREAD

**Issue by Ciantic** [react-tools/react-table#1141]
On this example, there is some bug: https://react-table.js.org/#/story/tree-table-hoc

It shows the filters jumbled on the top. As if there were extra column with nothing inside it.

Here is a screenshot using Google Chrome, I have tested also Firefox too:

![image](https://user-images.githubusercontent.com/64731/46309462-18329f00-c5c5-11e8-8ee0-961a7a089957.png)

Notice also how the last name filter input overflows it's area.

I think the example has something incorrect in it.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
