### ISSUE TITLE
Multisort Redefinition without ShiftKey

### ISSUE THREAD

**Issue by HtmlRanger** [react-tools/react-table#1152]
Hello! I want to rewrite the sorting so that the multi-sort works by clicking on Th without shift. I'm trying to replace

```
toggleSort = {e => {
             isSortable && this.sortColumn (column, e.shiftKey)
           }}
```
on

```
toggleSort = {e => {
             isSortable && this.sortColumn (column, true)
           }}
```

This works in the source code, but I don’t know how to do it in the properties of the component. Thus, I want the sorting to always work as if the shift is pressed. Can you help?

**Comment by marjan2k** [comment]
I'm looking for this too. Is there a way to do this currently? Documentations speak only of shift key.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
