### ISSUE TITLE
Use default sorting but handle the pagination server-side

### ISSUE THREAD

**Issue by erald14** [react-tools/react-table#1162]
I would like to handle the pagination server-side but use the default sorting of react-table.
as i understand when using manual as a prop the sorting disables.
Is there any way i can do that? And if not ,can it be added?

**Comment by tannerlinsley** [comment]
Do not pass the manual prop, but populate your data using the standard server-side approach. This is experimental, so proceed with caution. You can ask for more help/advice in the forum here: https://spectrum.chat/react-table

This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
