### ISSUE TITLE
 It is not possible to add a sub component from async

### ISSUE THREAD

**Issue by dazer91** [react-tools/react-table#1190]
Hi

When i create SubComponent and include component with async function for example in componentDidMount(), React-table don't create subcomponents, but when i remove this function React-table create component. Is there another method to create such functionality?

**Comment by Mulli** [comment]
I am using isLoading flag to display gif icon while data is not ready. Hope it helps.

**Comment by dazer91** [comment]
Thanks for your answer. I try this trick but when i start async function subComponent is deleted. When i deleted async function everything works.
I haven't any error in console.

For exapmle: 
<pre>
 &lt;ReactTable
      data={data}
      columns={columns}
      SubComponent={myComponent}
   />
</pre>
And myComponent is
<pre>
class myComponent extend React.Component {
  state = {
    isLoading: true,
    data: []
  }
  render(){
    return (
      &lt;div>
         {this.state.isLoading && &lt;span>Loading....&lt;/span>}
         {this.state.data.map(element => &lt;div>element.name&lt;/div>)}
      &lt;/div>
   )
  }
  componentDidMount(){
   this.asyncFunction().then(res=> this.setState({isLoading: false, data: res.data}))
 }
}
</pre>

**Comment by tommyalvarez** [comment]
@dazer91 The problem (same i'm having) is that React Table closes all expanded rows on data change... so when you fetch data for your inner subcomponent to display, data changes and react closes all rows giving you the illusion that you can't expand nothing and hence no subcomponent was created (but if you actually place a debugger in your componentDidMount just before _this.asyncFunction()_ call, you will notice that it's expanded and the loading state of your subcomponent is rendered briefly. Then when you continue the execution it dissappears again :(

It's supposed to be fixed by adding the props _freezeWhenExpanded_, and _collapseOnDataChange={false}_ to the parent React Table. However for me, that triggers infinit ComponentDidMount calls, don't know why, probably because on each data change, the subcomponent is remounted and fetch happens again and it goes on forever...

**Comment by tommyalvarez** [comment]
@gary-menzel references #791

**Comment by dazer91** [comment]
@tommyalvarez Thanks ! It's works
