### ISSUE TITLE
Issue with minResizeWidth props for columns.

### ISSUE THREAD

**Issue by visshaljagtap** [react-tools/react-table#1220]
I have set the minResizeWidth props value but It's not working.

I want to restrict the column width while resizing.

It will be great if I get solution. Thanks!

**Comment by jannikkeye** [comment]
I'll crosspost my answer from the PR as I see this issue here just now.

@visshaljagtap As far as I am aware there has not been a new release after this PR got merged. Are you installing react-table from npm? If so and you want to use this new prop then you should install directly from GitHub. But to be honest I would hold of on it until it either gets released or next major version is around the corner. While I did implement the prop in this PR we decided not to use It until a normal release arrives. Maybe you can do the same 👍

**Comment by jlhirond** [comment]
Some business requirements dictate that we wait for a new release to acquire this specific fix that we are waiting for. Not encouraging considering the last release shown on the releases page is May 2018.

**Comment by DevinWatson** [comment]
@tannerlinsley Can we get a new release asap?

**Comment by EugeneCib** [comment]
@jannikkeye I guess there are two issues with PR for minResizeWidth
1) I think currentColumn lookup is done by accessor, but should be done by ID
2) before using value of minResizeWidth from currentColumn, there should be check if it is defined on a column https://github.com/react-tools/react-table/pull/1135/files#diff-8b2b36b65495c258cbd342b7fe001e81R622

**Comment by tannerlinsley** [comment]
Just did a new release. Thanks for your patience!
