### ISSUE TITLE
Manual react-table never fetches pages > 0

### ISSUE THREAD

**Issue by JoshMcCullough** [react-tools/react-table#1230]
**Describe the bug**
Paging for manual tables does not work. `onFetchData` always indicates the page number is 0, even after clicking "next" to go to page 1.

**To Reproduce**
1. create a react table as linked below
2. click "next", watch the logs
3. see that page 0 is always in the state passed to `onFetchData`

**Expected behavior**
`onFetchData` should pass `page + 1` when I click "next".

**Codesandbox!**
https://codesandbox.io/s/q4z0zp6l6j

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser: Chrome
 - Version: 71.0.3578.98

**Additional context**
Manual table is essentially broken unless I'm missing something!

Similar or potential dupe of #1072.

**Comment by JoshMcCullough** [comment]
Temporary workaround is to use `onPageChange={page => this.setState({ page })}`, or similar. But `onFetchData` should still be passing updated rather than stale state.

**Comment by helissonms** [comment]
You never updates your current page on local state...

**Comment by JoshMcCullough** [comment]
That's the bug, react-table does not send the incremented page number in `fetchData`.

**Comment by helissonms** [comment]
Ok :)

**Comment by matheusb-comp** [comment]
Oh, I see. From my understanding of the [Fully Controlled Component](https://react-table.js.org/#fully-controlled-component) docs, once you pass the `page` prop, your component now controls of the `page` state, and you must also pass the `onPageChange()` callback.

In this scenario, the `page` you receive in the `onFetchData()` `state` should be ignore, since the source of truth is now your `page` state.

https://codesandbox.io/s/rwr89pw4yo
