### ISSUE TITLE
Fixed column

### ISSUE THREAD

**Issue by zuyetawarmatik** [react-tools/react-table#433]
Thanks for your great react table! I would like to ask if the component supports fixed column at the current version? Thank you.

**Comment by vaidsu** [comment]
I am also trying to find one. This table has been very useful so far, now when I tried to implement freezing columns left most, I was trying to play with styles, positioning etc., but since I have to use render the whole cell outer by myself, it will be great if we can have some form of built in. Is that possible or should we try on our own.? If yes, please suggest.

**Comment by tannerlinsley** [comment]
Sorry, but this is not currently supported.  It's likely not to land in future releases for a long time, so if that is a breaking decision, I'm so sorry!

**Comment by vaidsu** [comment]
Thanks for your response.

I understand the requirements and charter. But if we want to do it ourself,
do you have any suggestions? Like using styles or something.

I am trying wrap an outer div and making relative inner div with one column
fixed. But that seems to be difficult to manage for responsive screens.

Some hints will be great.

Thanks for your help.
Vaithi

**Comment by amitripshtos** [comment]
I would like to help writing that feature as well, but need a guidance since there are multiple ways to resolve it

**Comment by oldo** [comment]
+1 for this feature

**Comment by marf** [comment]
+1 for this feature

**Comment by tannerlinsley** [comment]
Please no +1 comments. Emails and notifications are sent for every one. Use the thumbs up on the issue description instead.

**Comment by dougaraujos** [comment]
For the time being, I am using the [position:sticky](https://caniuse.com/#feat=css-sticky) to freezing columns.
