### ISSUE TITLE
Still not possible to re-render rows that were modified?

### ISSUE THREAD

**Issue by cristianocca** [react-tools/react-table#451]
## What version of React-Table are you using?
6.5.3

Suppose I change some field on the row.original object, right now even a call to setState that justs sets again the list of rows object again won't refresh the visible data.

So far the only way to force the table to re render it's internal state, it's to either change the actual data reference or the columns reference. Is there a way to force a specific row to re render, or at least re render all rows but in a controlled way rather than changing data/columns references?

**Comment by corymainwaring** [comment]
I had this problem too, since the number of rows rendered in the table is fairly small, I found a way to get access to the table and save off either `fireFetchData` for server side data or `forceUpdate` the component to re-render when state has changed without using `setState`:
```javascript
<ReactTable {...props}>
{(state, makeTable, instance) => {
  this.state.invalidateTable = instance.fireFetchData
  // this.state.invalidateTable = instance.forceUpdate
  return makeTable()
}}
</ReactTable>
```

This probably shouldn't work, as I'm never using `setState` on my container component to set the invalidateTable function, but I got warnings to not use `setState` within the render method. So I tried this and it works. Maybe someone else with more knowledge of React state management can chime in with a better way to do this or why this is working without `setState`.

**Comment by cristianocca** [comment]
Does `forceUpdate` actually "reload" the rows data? I don't know enough of the table internals, but if I update the original data of a given row, or even the `row.original` from the callbacks you get on some components, it doesn't matter how many times I re render the table it will never load the updated values until I actually change something else like the table headers, even changing the rows list reference is not enough.

**Comment by tannerlinsley** [comment]
This is a very common question that spans all react component, not just react-table and involves using immutable data patterns to update the data, (usually using setState or some other immutable means of updating). 

For more help on this subject we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
