### ISSUE TITLE
Allow multiple footers

### ISSUE THREAD

**Issue by authentik8** [react-tools/react-table#453]
## What version of React-Table are you using?
**6.5.3**

## What bug are you experiencing, or what feature are you proposing?
The docs mention that one can add a Footer to a cell by adding JSX, a string or a function as the `Footer` key to a column configuration. It would be good if the `Footer` key also took a list of the above, allowing for the rendering of multiple Footer rows per column.

P.S. Thanks for the library, it's fantastic!

**Comment by tannerlinsley** [comment]
You could also just render 2 cells.  Since it accepts JSX, you could put as much or as little in the footer area as you want.  Don't think of it as a single footer property. It's merely a footer hook to do whatever you'd like :)

**Comment by EvanDarwin** [comment]
How does one "just render 2 cells?" You answered the issue but didn't describe how it's supposed to work, nor it is documented anywhere. ☹️

**Comment by imaan** [comment]
> How does one "just render 2 cells?" You answered the issue but didn't describe how it's supposed to work, nor it is documented anywhere. ☹️

For anyone who finds this in the future, an answer the above:

You can render several divs in the footer hook as long as they are encased in a singular parent div. 

With a little CSS work you can and easily style them to look like two footer rows. This is even easier if you just steal the existing styles for a table cell from the react-table css file.

I haven't done any of the styling here because I'm in a bit of rush, but here is an example of what I'm talking about:

https://codesandbox.io/embed/myn6x6580p

**Comment by EvanDarwin** [comment]
Thanks for the code @imaan -- I don't necessarily have this issue anymore, but others might!
