### ISSUE TITLE
Filter wait for input

### ISSUE THREAD

**Issue by jaydlawrence** [react-tools/react-table#470]
Using react-table 6.5.3

## What bug are you experiencing, or what feature are you proposing?
Add an optional timeout between firing `onFilteredChange` and firing `onFetchData`

## What are the steps to reproduce the issue?
When doing server-side filtering, every keyboard press in a filter input field calls `onFetchData`.
This then fires off multiple requests to the backend while the user is typing.

A possible work around could be to allow an optional timeout on every `onFilteredChange` before firing `onFetchData`. This timeout could then be cancelled if another `onFilteredChange` is called or onFetchData is called from elsewhere before the timeout ends.

Otherwise, what would be the best way to get around this issue?

**Comment by tannerlinsley** [comment]
You need to `debounce` your call to the server.

Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!

**Comment by danielsetreus** [comment]
I realize that this is a very old issue, but I don't agree with this being about implementation. Since react-table calls `onFetchData` together with `onFilterChange` there is no easy way to determine if the call to `onFetchData` should be considered as "real", or if the user is still typing.

The only real wayI see is to always wait for a number os seconds befor making server request - but since that will affect pagination as well is not really an option.

I would suggest an event middle-man that defaults return true, but that you could implement yourself to handle a waiting period (return false). Meaning that, when filters change, `react-table` calls this middle-man first to determine if a new fetch should be made.

Sort of (filters changed) -> `filtersShouldFetchData` -> `onFetchData`
