### ISSUE TITLE
Editable example doesnt work properly on sorted column.

### ISSUE THREAD

**Issue by smoleniuch** [react-tools/react-table#519]
## What version of React-Table are you using?
Newest

## What bug are you experiencing, or what feature are you proposing?
In some cases after column is sorted, edition that occures on the cell applies to another  too.
## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
[Sandbox](https://codesandbox.io/s/n5r19gzQP?from-embed) - docs example
[YouTube demo](https://youtu.be/bZYfroTlZyE)
## What are the steps to reproduce the issue?
1. Make column sorted.
2. Apply changes to the row that doesnt have unique value,and it makes rows change positions.

**Comment by tannerlinsley** [comment]
Interesting. I wonder if this could be happening because of the editable content strategy. Does this happen when using an input box?

**Comment by gary-menzel** [comment]
I think this *may* be a partially due to a visual glitch. Once the data is edited in the sample it is pushed back into react-table and then immediately resorted (so the field you edited has moved based on the sort). If you switch pages, the data then "rights" itself.

Happy to be proven wrong, but when I did a test with the provided Sandbox and entered '1' after the first 'ability' (in the top left cell) it was reordered to a different row - it is leaving a "ghost" in the DIV. But, if I switched pages, the "ghost" left behind by the edit being in the selected DIV went away because that cell is then re-rendered (i.e. DIV still contains the edit content and is not being updated by the redraw from the sort - I don't think this is a bug, it is a HTML DIV issue... see following).

I'm using a variation of the sample that does not use `dangerouslySetInnerHTML` but renders the content from the `data` directly - which will be re-rendering the content (so I don't have this problem). In my `renderEditable` function I pre-grab the row and col indexes and pull out the value of the data item then just drop it into the content of the `<div ... >{dataValue}</div>` (in my case it also has some escaping wrapped around it - but that is the essence of it).

So, the sample is probably marginally "broken" but, I found I had to do a lot more to get a fully operational and integrated cell editor going. It's only a basic sample and will depend on your editing strategy. Also, if you want to update your external data (i.e. the data as it is being pushed in as props) then you need to take into account the paging of react-table as the row and col indices are local to the page (and may not directly match the positions in your data). I have actually passed a "key" field to my editing HoC so that it can send the write data back to the update callback. That HoC also handles vertical movement between cells on the page by adding in a keyhandler.

**Comment by gary-menzel** [comment]
Closing this issue as it is more related to implementation than a bug with react-table itself. You can ask for further assistance on the react-table slack channel or stackoverflow. Thanks.

**Comment by szviragh** [comment]
I ran into the same issue.
I thought, i will find the answer in the [samples](https://react-table.js.org/#/story/editable-table), but it has the same implementation issue.
Could you correct the editable-table sample? Thanks.

**Comment by gary-menzel** [comment]
@szviragh This is just how it works - you are changing the data so the sort is triggered. Editable rows are just an "example" and need to be tailored for your specific implementation (that is, there is no way to "fix" the editing so it work in every situation).

**Comment by gideon-grossman** [comment]
Can someone provide an example of preventing a resort when a cell is edited?
