### ISSUE TITLE
Question: Horizontal Table

### ISSUE THREAD

**Issue by SCasarotto** [react-tools/react-table#532]
First I wanted to say, awesome library! I love it and am planning to use it heavily moving forward on multiple production applications.

I had a thought today and didn't quickly see the answer in the docs. Is there any way to flip the table to be horizontal, with the headers on the left and the data as columns?

**Comment by gary-menzel** [comment]
If you mean like a fixed column - no.

But you if you want to flip then that is more easily done in your own code by morphing the data before you provide it to react-table.

**Comment by SCasarotto** [comment]
Ah, I might have misspoken. a vertical heading (https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_headers). If not it's okay. Thanks.

**Comment by gary-menzel** [comment]
Well - that is the second part of my comment. Essentially, the way to do that is reorganise your data to flip it and then build some type of formatting rule (probably by overriding cell props) to give the bold heading style.

However, my first point still stands. That "heading" will still just be a column and if your data needs to scroll horizontally, that "heading" will scroll to the left (it can't be fixed in the current code base features).

**Comment by gary-menzel** [comment]
If you need more implementation help, you should probably ask on the slack channel or on stackoverflow.

**Comment by SCasarotto** [comment]
No problem. Thanks for the quick answer.
