### ISSUE TITLE
Dynamic styling by getTrProps function for background color issue

### ISSUE THREAD

**Issue by how30013** [react-tools/react-table#558]
## What version of React-Table are you using?
v6.6.0

## What bug are you experiencing, or what feature are you proposing?
Hi, there.
I am trying to do highlighting specific row and change its background color by using getTrProps function.
But its behavior seems to be strange while I also filter the data.
The background color does not be reset to the original color when the filter is reset.
In the meantime, if I am not going to change its background color but add a border on it, the code just works fine.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

background highlighted
https://codesandbox.io/s/l7lmpx2y99

border highlighted
https://codesandbox.io/s/3yllpp7z6p

## What are the steps to reproduce the issue?
Both examples are from official examples.
Just added a styling rule for the Age above 20.
Type on the filter of the age column, e.g., 25,  to make the whole page is highlighted then clear the filter, and you can see the difference.

And thanks for this library.

**Comment by gary-menzel** [comment]
This is related to your CSS colours.  If you use 'inherit' rather than 'none' it seems to work as you have specified (you could specify a colour rather than 'inherit').  I only tried this on the "background highlighted" one.

Also, as this is implementation related, it should be discussed over on the #react-table Slack channel (there's a badge to be able to join at the top of the docs). Thanks.
