### ISSUE TITLE
React rows height

### ISSUE THREAD

**Issue by razvanitu** [react-tools/react-table#570]
Hi,

Does someone use computedHeigth ? I mean , when in a cell you have a picture or long text , the row should auto-adjust it's heigth.

I did not find any prop for this, can you help ?

**Comment by gary-menzel** [comment]
I haven't tried it with an image but I have text in multiple divs in a cell and the row automatically adjusts. Maybe you should try with an image.  If it is only a single line of text, then that does NOT wrap (it uses the overflow ellipsis in css to truncate the text) but you can override that yourself using the getProps on the column or getTdProps for the cell.

However, this is really an implementation question rather than any issue with react-table itself. Please join the #react-table Slack channel to get more help. There's a badge at the top of the doco. Thanks.
