### ISSUE TITLE
How to access to another column's value from a column

### ISSUE THREAD

**Issue by jingyao97** [react-tools/react-table#571]
I have a column named "Status" and another column named "Action"
Under default situation, all action will be "edit"
However when status is "canceled" action should become "delete".
How can i make this?

**Comment by mikedevita** [comment]
you can access the entire row's data via the `Cell` property in the columns.


```es6
const columns= [
    {
        Header: 'Some Other Column',
        accessor: 'SomeOtherColumn'
    },
    {
        Header: 'Column 2',
        Cell: ({ row, original }) => {
            return (<span>
                {original.SomeOtherColumn}
            </span>)
        }
    }
]```

**Comment by gary-menzel** [comment]
Mike is correct. Use a custom `Cell` - check the doco for more details.

Also, please join the #react-table Slack channel for questions of this nature rather than using the github issue facility.  This is mainly for the development pipeline and reporting bugs. You can find a badge at the top of the documentation. Thanks.
