### ISSUE TITLE
onFetchData causing column sorting to trigger onFetchData callback

### ISSUE THREAD

**Issue by shaun-sweet** [react-tools/react-table#606]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
"react-table": "^6.5.1",

## What bug are you experiencing, or what feature are you proposing?
When using the property for server side pagination ```onFetchData``` it mostly works great.  Pagination is perfect and works exactly how i want!  However, I'm wanting to use the column filtering the way it works out of the box and not have it trigger my onFetchData callback..  Currently, from what I've read/toyed with, I don't think that is possible?  Any thoughts?  Perhaps I missed something in the docs or am going about this incorrectly? 

I've attached a gif of the console open (it logs the state of the onFetchData callback).  First I show the pagination feature working great, then I show the column filtering.  

Thanks for the awesome library!

## What are the steps to reproduce the issue?
https://cl.ly/3J1f3F3B1E0B

**Comment by shaun-sweet** [comment]
actually, i believe this is due in part by the ```manual``` prop.  It seems thats responsible for the sorting NOT happening and the onFetchData is responsible for sending the fetch on the sorting click.  TBH I wish I could control what portions I want onFetchData to trigger on.  Instead, i think the only solution is a full custom one, but I'm unsure how to keep native column sorting... I like the default.  I'd be open to submitting a PR for more granular onFetchData triggers though.

**Comment by gary-menzel** [comment]
The doco does say that `onFetchData` is for handling all the data change requests (sorting, filtering, pagination) outside of react-table. So you are correct, setting `manual` indicates you will handle everything. In many cases, depending how you architect your applications, `onFetchData` may not be necessary at all (if you manage your data calls to the server outside of your components already).

However, a PR request for new functionality is welcome but would need to ensure that it doesn't break any existing functionality (i.e. those using the api in the current way would not be required to change what they are doing).

**Comment by shaun-sweet** [comment]
Thanks for the quick reply @gary-menzel 

I understand your point about the PR.  Perhaps I don't need onFetchData then.  I basically want to manage pagination manually while the sorting remains default behavior.  Do I need to set manual to accomplish this?  Perhaps you could point me in the right direction?

**Comment by gary-menzel** [comment]
When you say you want to manage pagination manually, are you saying you want to populate the data in the table virtually, progressively adding pages of data ?

If that is the case, then react-table may not be the right package for your use case. It doesn't support the progressive population of the data.

If you mean you want to just load a page at a time on the server but still have ReactTable do the sorting and filtering, I am not sure how that can work (because your server-side request won't know what data to pull in unless it pulls in everything - in which case, there is no need to use `onFetchData`).

With `onFetchData` you handle everything server-side but all the data is still pulled back for the specified criteria.  The main use is for very large data sets (so you only pull back one page of data at a time but you still need to handle your filtering/sorting as well).
