### ISSUE TITLE
[Feature] Allow locking of columns so they don't scroll and are always visible

### ISSUE THREAD

**Issue by TrevorJamesH** [react-tools/react-table#613]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?

New feature to allow locking columns to the left so they don't scroll and are always visible, same as the header. Should be implemented with a single prop: 'fixed' or 'fixed-left'. The prop can be set statically by setting the prop in the column definition, or controlled by passing a variable.

**Comment by gary-menzel** [comment]
This has been requested and looked at several times and is currently not on the roadmap. The reason being that ReactTable currently uses flexbox for sizing cells. There are a lot of moving parts when freezing a column and it may not be possible in ReactTable until flexbox is replaced by `grid` - which is currently not fully supported across all browsers.

Having said that, the proposal to use a simple property (like `fixed`) would be how it would be implemented.

**Comment by gary-menzel** [comment]
This will be closed for now because it is not on the current roadmap. However, it may be considered for a future version (and is already flagged in other feature requests).

**Comment by philmcp** [comment]
Building on @gary-menzel's "fixed" solution, I was able to naively get this outcome using the following SASS/CSS:

`    &.three-static {
        $first-col: 160px;
        $second-col: 140px;
        $third-col: 70px;
        .rt-td,
        .rt-th {
            &:nth-child(1),
            &:nth-child(2),
            &:nth-child(3) {
                position: absolute;
                background: #000000;
            }
            &:nth-child(2) {
                margin-left: $first-col;
            }
            &:nth-child(3) {
                margin-left: $first-col + $second-col;
            }
            &:nth-child(4) {
                margin-left: $first-col + $second-col + $third-col;
            }
        }
        .-headerGroups {
            .rt-th {
                &:nth-child(2) {
                    margin-left: $first-col + $second-col + $third-col;
                }
                &:nth-child(2),
                &:nth-child(3) {
                    position: relative;
                }
                &:nth-child(3),
                &:nth-child(4) {
                    margin-left: 0px;
                }
            }
        }
    }`

`	<ReactTable defaultPageSize={15} className="three-static"
					style={{
						height: "615px" // Must match num rows * row height
					}}
				/>`

The only drawbacks are that you'll need to:

- Limit your table height to perfectly match the number of rows show (otherwise the fixed columns will overflow)
- Hard code the column width's to match those values set in the CSS

**Comment by gary-menzel** [comment]
Yeah - this is the problem - which can probably be solved by using `grid` once it is fully supported in all browsers.  Otherwise, the base code just needs to be re-written to be more calculation intensive (which is outside of the design goals).

You can introduce a "type" of fixed column - at the expense of other features (like being able to drag for column sizing) and variable height rows - etc.

**Comment by dcworldwide** [comment]
I realise this is closed, but I would like to cast my vote for this feature. It's very useful to preserve user context when navigating a table with many columns.

**Comment by gary-menzel** [comment]
This will not happen until a full redesign of ReactTable.  Several people have attempted it (including myself) and there are just too many challenges to do it in the current architecture.

**Comment by apunov** [comment]
Definitely an upvote. Two obvious things are missing currently are: fixed and draggable columns.

**Comment by dcworldwide** [comment]
I don't see why a FR should be closed. Especially a popular requirement such as this. I don't like the negative stance that's been taken on this issue as afterall this is a foss project. We need an open issue to centralise and capture the conversation on how to implement this feature. Who cares if its long running.
