### ISSUE TITLE
Manually trigger sorting function of header?

### ISSUE THREAD

**Issue by TuanDSE62171** [react-tools/react-table#614]
## What version of React-Table are you using?
`"react-table": "^6.5.3"`

## What bug are you experiencing, or what feature are you proposing?
I have this kind of table where I have designed  for it to be able to drag n drop between columns, therefore it breaks the sort function of the header (because the `onClick` event was handling drag), so I figured that if the starting column and end column is the same it would trigger the sort function instead. The problem is I can't find any docs about that, I tried `handleOriginal` but it's not a function in `getTheadProps`

**Comment by gary-menzel** [comment]
This is more of an implementation question and is not a bug.

One solution would be to make a specific "drag" handle rather than use the whole column cell. If they click on the cell, it sorts, if they click on the drag handle then you can move the columns around. You should take it over to the #react-table Slack channel where other people may have other solutions. The other thing to consider is that you may be stopping propagation with your drag/drop functionality.

I've separated out the column ordering process from the actual columns (it's in a separate popup) - so it is not an issue for me.
