### ISSUE TITLE
Using Imported Components With Cell

### ISSUE THREAD

**Issue by trabur** [react-tools/react-table#617]
For some reason react-table renders the column on page load but when I start to page through the data any column with an imported component doesn't seam to be rendering...
```js
  Header: "Estimate Status",
  id: "estimateStatus",
  minWidth: 150,
  accessor: row => row.estimateStatus,
  Cell: row => (
    <EstimateLabel status={row.value} />
  )
},
```

**Comment by gary-menzel** [comment]
Your code snippet looks OK to me.  I have quickly tested using a component in the way you have above (the component tested was very simple) and I don't experience what you have described (i.e. it works as it should and displays correctly in page changes).

You should create a codesandbox.io example of the problem showing all the code to validate the behaviour. Otherwise this issue will be closed if the situation can't be reproduced.

**Comment by gary-menzel** [comment]
I've revisited this and tested with both a smart component (`extends React.Component`) and a pure component (function based) and `Cell` behaves as expected and renders correctly between page changes.

If you can reproduce this in a codesandbox.io page then please open a new issue.
