### ISSUE TITLE
How to filter on un-displayed properties

### ISSUE THREAD

**Issue by blackjackkent** [react-tools/react-table#625]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
Not precisely a bug, but I am unsure if there is a feature for what I want or not. I would like to be able to dynamically, externally filter the table based on a property on the source data object which is not actually displayed as a column. Is there a way to make this work? 

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/lpk8r8rrz9

The table in the above sample filters based on the "isVisibleWhenFiltered" property; I'd like to be able to filter down to just rows where that property is true, without actually having to have an "Is Visible When Filtered" column in the table.

Thanks a lot for this library; it's proven super easy to get up and running with and this is the first hiccup I've run into. :)

**Comment by gary-menzel** [comment]
If you don't specify a column that is filterable, ReactTable won't filter on it. This is because the design behind ReactTable is very visual so if  user can't see the data then it is not filtered.

You'll need to filter the data externally on that (or other) properties before passing it into ReactTable.

**Comment by blackjackkent** [comment]
Okay, cool, good to know. Thanks! :)
