### ISSUE TITLE
Filter with custom cell does not work properly

### ISSUE THREAD

**Issue by giggioz** [react-tools/react-table#631]
React Table 6.7.4

I have a custom cell in Last Name column (2nd column) which implements an ImagePreview component: if you pass your mouse over a cell in that column you see an image preview. This is fine.
**Unfortunately if you try to filter this column typing some text in the filter cell it does not work properly.**

**If you comment the custom cell at line 44 in index.js it works fine.**

https://codesandbox.io/s/5x8opmk40p

What am i missing here?
Thanks!

**Comment by gary-menzel** [comment]
The short answer is that the `<ImagePreview />` component does not seem to be updating its' content when the row is changing.  If you just return `row.value` from that `Cell` function then it works correctly.  So it is really outside of the scope of react-table to resolve. You may have to make the component in `Cell` be a little smarter and cause an update in some way so that the text for the row is rendered correctly.

**Comment by giggioz** [comment]
Thanks for the insight.

I've added this lines to ImagePreview Component:

```
 componentWillReceiveProps(nextProps) {
   this.setState(nextProps)
 }
```

in this way the component re-renders with the new props... and now it works!

https://codesandbox.io/s/zl99mm6x1x

@gary-menzel is this what you meant?
Thanks again.

**Comment by gary-menzel** [comment]
Well - without seeing that component - yes - that is one solution.

You could also make the `<ImagePreview/>` component be a "pure" component - rather than a "smart" component - and just use that prop directly (and you would not need to manage any component state.

[But, that might not be appropriate - hard to tell without knowing the long term purpose of `<ImagePreview/>` - if it is only for display, make it a "dumb"/pure component.]

**Comment by gary-menzel** [comment]
[if you are already using `state` to manage the hiding and showing of the image - then you've probably got the best answer already]

**Comment by gary-menzel** [comment]
So, to summarise, the Filter was working correctly, however the `<ImagePreview />` component was statically rendering the initial content of the cell (and the cell content changes when the data is filtered). By re-rendering the `<ImagePreview/>` component you are updating the cell to the latest content.

**Comment by giggioz** [comment]
You can have a look to the component in the codepen https://codesandbox.io/s/zl99mm6x1x

He's already smart: it has state to mange the show/hide image on mouse over as you thought.

**Comment by gary-menzel** [comment]
OK - well based on looking at that - you probably don't need to store the text and the link in `state` as they never change - you could just use them direct from this.props (e.g. `this.props.articleName` - and you could also pass the link in if that changes with each record) and then you would not need `componentWillReceiveProps`.

The props changing on the component will automatically make it re-render.

**Comment by gary-menzel** [comment]
[well - they never change internally to the component]

**Comment by gary-menzel** [comment]
I've forked it and made the changes I'd recommend - including using => functions instead of `bind` - sort of makes it cleaner/clearer.

https://codesandbox.io/s/lyy40rwkk7

In any case, this is implementation related. The best place to get answers for things like this is the #react-table Slack channel (there is a badge at the top of the README in the doco). Thanks.

**Comment by giggioz** [comment]
🥇 🥇 🥇
