### ISSUE TITLE
make vertical scroll bar stay fixed in view area when scrolling horizontally

### ISSUE THREAD

**Issue by DavidIMcIntosh** [react-tools/react-table#658]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
If your table has both a vertical scroll bar and a horizontal scroll bar, then when you viewing the left-most side of the table, i.e. horizontal scroll bar is all the way to the left, the vertical scroll bar is scrolled off to the right and not visible.

**Comment by gary-menzel** [comment]
That is, unfortunately, how it works. ReactTable was not actually designed to have a vertical scroll bar because it is a page-based solution (despite the `height` being added).  Unfortunately, there is no easy way to fix this without completely redesigning how ReactTable works. [My own personal opinion is that it shouldn't have the `height` and vertical scroll bar]

HOWEVER - if you can find a backwards compatible solution and what to submit a PR then it will be reviewed and merged accordingly.

**Comment by gary-menzel** [comment]
@DavidIMcIntosh did you find a solution for this?  If not, I will close this until someone can submit a PR. It might have to hold over until a new major version.

**Comment by gary-menzel** [comment]
Closing this for now. Happy to reopen with a PR.

**Comment by fabio-grieco** [comment]
try with the Tbody prop-callback: 

`                  getTbodyProps: () => {
                        return {
                            style: {
                                overflow: "visible"
                            }
                        };
                    },`
