### ISSUE TITLE
Cursor being moved to the end of input on each key stroke

### ISSUE THREAD

**Issue by monners** [react-tools/react-table#672]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
When typing in a filter input, the cursor is moved to the end of the input on each keystroke.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
This behaviour is present in the react-table examples:  See [controlled-component](https://react-table.js.org/#/story/controlled-component)

## What are the steps to reproduce the issue?
1. Type some input into a text input below the table header
2. Move the cursor to somewhere other than the end of the input
3. Type another character (and see that the cursor jumps to the end)

**Comment by gary-menzel** [comment]
This is easily reproduced but requires investigation to understand why it happens and how to fix it.

**Comment by gary-menzel** [comment]
On review this issue is more complex that it appears to be.  It seems to be happening when the `onFilteredChange` and `filtered` props are used.  If those are removed, the `filter` input works correctly.  I suspect this is related to the `filtered` prop changing and causing the `render` method to be triggered.

**Comment by monners** [comment]
@gary-menzel Any chance you can point me in the right direction as to where I should probably be looking in the codebase?  Can do a bit of spelunking this weekend.

**Comment by gary-menzel** [comment]
Well - essentially - it is the pushing of the `filtered` data back into ReactTable that is causing the render to happen.  I think the essential problem is that the `<input/>` component needs to be controlled locally (internally) rather than at the wrapper level.  So, because you can override the `FilterComponent` that is up to the developer to do.

**Comment by gary-menzel** [comment]
On further review, I no longer consider this a "bug". It is really an implementation question that can be address by overriding the `FilterComponent`.

**Comment by monners** [comment]
Thanks for getting back to me.  Any chance you can point me toward an example of overriding the FilterComponent?

**Comment by gary-menzel** [comment]
Well - it is just a React component.  There is a "Custom Filtering" example in the doco but it focusses on creating a dropdown.  But it still contains the core. The real trick would be ensuring you have state in your component that managed the `<input/>` field.  One downside would be that you would not get "real time" filtering - you'd only call the filter change callback when you blurred the input or pressed ENTER or such. That would be the easiest way.

Otherwise, you would need to use browser tools to get where the cursor was and remember it for when the component redraws and then reset it when they click somewhere else.

But no specific examples to do exactly what you are wanting to do.
