### ISSUE TITLE
React Transition Group

### ISSUE THREAD

**Issue by nest-aka-swan** [react-tools/react-table#692]
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
I would like to animate enter and exit of data rows with React Transition Group but I'm getting errors:
```Warning: Unknown event handler property `onExited`. It will be ignored.``` and ```Warning: Received `true` for a non-boolean attribute `in`.``` Is there any proper way to do this?

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/p56wxv367

## What are the steps to reproduce the issue?
Click on `Remove one item` button

Thanks in advance

**Comment by gary-menzel** [comment]
However, I don't remember seeing anyone talking about using React Transition Group with ReactTable - it looks like you are on the right track but...

The issue that you will be hitting is that the props in ReactTable are all validated as of 6.7.5 and, as those props are not known by the existing components they are triggering an error (and I suspect are not being passed through due to the prop validation).  The problem, of course, there's no easy way to remove the propTypes without editing the code.

Normally I would suggest this be taken over to the #react-table Slack channel but I think this may need to be considered as a correction to the code (if we can find a way to do it and retain the existing props validation).

@frankolson & @tannerlinsley might want to provide an opinion in regard to this. Possibly a little too tight given how much can be overridden and what props a developer may need to pass ?

**Comment by tannerlinsley** [comment]
Although this is possible, I am not sure how just yet.  It's definitely edge case and I may get around to it some day (not soon, and it would be out of curiosity).  For the time being I would not recommend animating the table elements (mostly out of respect for UX), but hey! react is about doing your own thing.  You are more than welcome to try this out (every root component is overridable in the props), but there will be no official support for this in the time being.  Let us know if you figure it out! We would love to share it in the wiki :)

**Comment by chriscerk** [comment]
If anyone is interested, got this working with 
```javascript
<tbody {...getTableBodyProps()}>
 <TransitionGroup component={null}>
{rows.map((row, i) => {
            prepareRow(row);
            return (
              <CSSTransition key={yourUniqueDataKey} timeout={yourTimeout} classNames="yourClassName">
// etc...
```
