### ISSUE TITLE
How to do render a column if it receives data that includes html tags ?

### ISSUE THREAD

**Issue by Pasichnyk** [react-tools/react-table#703]
react-table 6.7.6

## How do I render a column if it receives data that includes html tags? 

eg. My data: 
```javascript
[ 
   {
      id: 1, 
      text: "aa<br/>bb   <br/>cc"
   },
   {
      id: 2, 
      text: "bbbb <br/>   cccc"
   }
]
```

How to do it properly?
Thanks.

**Comment by Pasichnyk** [comment]
Is there the only one way:
```javascript
dangerouslySetInnerHTML={{__html: cellInfo.value}}
```
Or it has some built in solution ?

**Comment by gary-menzel** [comment]
There is no built in solution.  But there are plenty of libraries that can convert HTML to React (and vice versa). But, it depends on your use-case....

If you want it to render real HTML then a conversion makes sense.

If you want it to render things like the less-than and greater than signs (so they can be editable) then you need to encode and decode them appropriately.

In your specific example you could use some type of search and replace when you render in a `Cell` handler to turn the `<br/>` tags into newlines.  If it is something you are doing often, create some sort of String Utils library that you can use to convert back and forth.  You may also want to consider stripping the tags out in a different function and returning that as the result of the `accessor` function (because that value is what is used for searching and filtering).

Having said all that, there is nothing "wrong" with dangerouslySetInnerHTML as long as you know why you are doing it.

However, this is an implementation issue and is best taken to the #react-table Slack channel (there is a badge at the top of the README in the doco).  Others may have different recommendations. Thanks.
