### ISSUE TITLE
Access props passed to ReactTable within a custom cell

### ISSUE THREAD

**Issue by ankit-m** [react-tools/react-table#711]
Is there a way to access props passed to ReactTable from within a custom cell renderer.

**Use Case**
I am passing redux actions via props to the table. I want each of the cells to have access to these actions. Currently, I am passing those actions within the accessor along with the data. This feels like a hack. Is there a cleaner way to do this?

**Comment by gary-menzel** [comment]
Firstly, I am not sure what you mean when you say you are passing them inside the accessor.  It sounds as though you are placing rendering functionality inside your accessor.  The access should return a pure value (and not a rendered component) as this is the value used for sorting and filtering.  It may not be causing issues now but it will eventually.

Without seeing an example of what you are trying to do it's a bit difficult to give advice. However....

If you are trying to do something like place a button on each row that triggers any action (Redux or otherwise) then it should be done inside the `Cell` prop.  I'd recommend NOT passing the action directly but calling a local handler that then calls the Redux action passed in to the component.

There are plenty of other overrides if your outcome is more complex than that (where you can add new props with `getProps` on the column or `getTdProps` on the ReactTable instance - and then override `TdComponent`) but I would not expect that to be needed in this case.

If this is not clear then you will need to spike up a codesandbox example of what you are trying to do for further review.

These issues are only monitored by a small group of people.  If you want access to a wider user base then you should join the #react-table Slack channel (badge at the top of the README in the doco).

**Comment by ankit-m** [comment]
```javascript
cols = [
  {
    Header: 'Col 1',
    Cell: (cellProps) => {
      return <CustomCell {...cellProps} onAction={() => {  /*call redux action here*/ }}   />
    },
    accessor: 'name'
  }
];
```

Based on your comment, this is how it looks now.
