### ISSUE TITLE
Change HTML element of table.

### ISSUE THREAD

**Issue by leonardovillela** [react-tools/react-table#734]
Can i change the HTML element of table, today is a `<div>`, i would to use `<table>` element, it is possible?

Same for other elements of react-table.

**Comment by gary-menzel** [comment]
This is not recommended.  All the elements are designed to be a `div`

**Comment by leonardovillela** [comment]
Thanks for the answer, but why it is not recommended?

**Comment by gary-menzel** [comment]
That is because ReactTable is styled specifically around `divs`

**Comment by tannerlinsley** [comment]
React Table uses flex box and complex nesting of divs to support headers and footers, wrapped table components, row expansion and nesting... to do all of this in normal table elements is simply impossible without violated HTML spec which forces table elements to be direct descendants of each other in a very particular order.

**Comment by haukepribnow** [comment]
I was also looking for a way to replace the `<div>`s with "true" HTML table tags. My main intention was to allow the column structure to be kept intact when copying & pasting the grid content to Microsoft Excel (AFAIK without a true HTML table structure, Excel just puts all content into one single column instead of copying the two-dimensional structure successfully). Making the grids more accessible for screen readers and the such may be a relevant case for "true" HTML tags as well.

Too bad that the HTML specifications do not seem to offer nested `<tbody>` tags or some kind of "dummy" tag that could be used instead of the `rt-tr-group` `<div>`s. Judging from my short research, the other tags would match quite nicely:

- `rt-table` = `<table>`
- `rt-thead` = `<thead>`
- `rt-tr` = `<tr>`
- `rt-resizable-header` = `<th class="resizable">`
- `rt-td` = `<td>`
- `rt-tfoot` = `<tfoot>`
- `rt-tr-group` = ??? (Here's the core issue.)

Obviously, this would also require additional CSS to override the browser default styles for table elements with the styles that `react-table` requires in order to work.

Is there anything I missed that could violate HTML specifications except of the `rt-tr-group` mismatch?

**Comment by gary-menzel** [comment]
This requires a complete re-write of ReactTable due to Tanner's original comment and the internal reliance on `flexbox`.  It would also violate the original principal to make ReactTable page-based and mobile friendly. If a "real" HTML table is required, then ReactTable is probably not the right package or you might require some background "magic" to copy the data into a hidden table first and then copy to the clipboard from that (if it is possible).

**Comment by manu1222** [comment]
I wanted to use bootstrap table classes, and then I found this issue and now I found that it's not possible. Anyways, no issues. DIVs are awesome.
