### ISSUE TITLE
Pivoting nested array

### ISSUE THREAD

**Issue by Romyeo** [react-tools/react-table#738]
Been using react-table for a while now, but im having trouble displaying an array of object and each object there's a nested array of objects.

ex. data structure:

```
const arrOfObj = [
  {
    name: 'Janey Doe',
    points: 10,
    nestedArr: [
    	{
      	month: 'January',
        points: 2
      },
      {
      	month: 'February',
        points: 5
      },
      {
      	month: 'March',
        points: 3
      }
    ]
  },
  {
    name: 'Johny Cash',
    points: 12,
    nestedArr: [
    	{
      	month: 'January',
        points: 5
      },
      {
      	month: 'February',
        points: 5
      },
      {
      	month: 'March',
        points: 2
      }
    ]
  },
]
```
Expected output

```
Name                   Month                      Points
Janey Doe                                           10
                       January                       2
                       February                      5
                       March                         3
--- ETC
```

I can toggle 'Janey Doe' or the name value to show the months.
How can i do or display this with pivot without using aggregation? since the data is already aggregated in the back end.

**Comment by gary-menzel** [comment]
Because your data is already pivoted and aggregated, you can't really use ReactTable to display it. You either have to provide the data to ReactTable in a "flat" format (and then pivot and aggregate there) or you would have to build a specific component that knows the structure of your already pivoted data.

In other words, the current version of ReactTable does not allow you to use the nested array for the pivot data (it calculates it all internally and does not expose that directly).  If you do look at the internal state, you will see that it creates (and maintains) a `_subrows` object inside the pivot row.

**Comment by Romyeo** [comment]
@gary-menzel I see, well i still could use the subcomponent module but my only concern is that when i sort the column 'month', can it sort the subcomponent or i should listen to that event since its in tableProps and just sort it manually?

**Comment by saadiya-kazi** [comment]
any updates on the same issue ?
