### ISSUE TITLE
Server side data, client side sort and filter

### ISSUE THREAD

**Issue by mrceperka** [react-tools/react-table#741]
Hello :wave:, quick question. Is there any way, how to **combine both server side sorting, filtering, ... and client side**?

Let's say, that I have _outsite table filters_. There are also filters provided by react-table. I would like to use that react-table filters for client side sorting, but still do server side request while paginating.

I have played with `instance.getResolvedState()` and `instance.getSortedData()`, but it did not end up well.

Thanks :wave:

**Comment by gary-menzel** [comment]
Not really. You are eventually going to hit synchronisation or race condition issues (unless the split is clearly either client side or server side).  This is because, to ReactTable, there is only ONE source of truth - and that is the `data` prop that gets passed in.  If you are using `onFetchData` to create the state for the `data` prop (in some way, either in the component `state` or via global store or some other mechanism) and you then use an internal sort or filter, ReactTable is still going to call `onFetchData` and your server-side rules will kick in.

The purpose of `onFetchData` is mainly for very large data sets that you don't want to load into memory (think of a log table - for example).  Having said that, ReactTable can handle filtering and sorting 100s of thousands of rows.

**Comment by mrceperka** [comment]
I could probably use `onPageChange` to fetch new data. But if the fetched data would fit the size of the page (and they would), they would be displayed on the first page, while the table would be at the next page. Therefore, I'd see `No results` text. I have already tried this.

Could the hook with similar functionality as `onFetchData` has be added? Hook would be triggered in the same situations as `onFetchData`, but the table would still perform sorting and filtering. Is that possible/meaningful?

**Comment by tannerlinsley** [comment]
You could technically build your own pagination component and fetch the data on your own.  You could then feed the data into a non-server-side react-table instance and it would allow sorting and filtering on that data.  This would be strange IMO, but if that's what you need, then that's possible.

Given this is more of an implementation question, let's move the discussion to the slack channel (you can sign up by clicking the slack badge in the readme).  Thanks!
