### ISSUE TITLE
Page Jump buttons won't trigger in Firefox

### ISSUE THREAD

**Issue by rovnyart** [react-tools/react-table#768]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
When using Mozilla Firefox (currently v.57.0.4), the page-jump buttons (^ and v) wont' trigger until i put the caret inside page number field by my own. (There is no such problem in Chrome, but pages are still not jumping until i click outside page number field or hit Enter. I think, this is a quite uncomfortable behavior)

## What are the steps to reproduce the issue?
1. Launch Firefox
2. Go to any react-table tutorial page, e.g. [this](https://react-table.js.org/#/story/server-side-data)
2. Try to change pages using page jump "v and ^" buttons.

**Comment by gary-menzel** [comment]
I don't think this is a bug with ReactTable.  The spinner button is being put there because of the `<input type="number" />` tag (it is nothing that ReactTable is doing).  The type is `number` so that the browser restricts the input to a number (without having to load other external dependencies - which is a core requirement of the build for ReactTable).

The spinner button is actually a non-standard feature as per this:

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-inner-spin-button

Here are some suggestions to disable it in your own CSS (but as this is not a ReactTable issue and ReactTable tries to be agnostic - it is unlikely to be added to the library itself).

https://stackoverflow.com/questions/3975769/disable-webkits-spin-buttons-on-input-type-number
