### ISSUE TITLE
onPageChanged is not called when data is being filtered

### ISSUE THREAD

**Issue by DamianFekete** [react-tools/react-table#782]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
If you're passing `page` and `onPageChanged` to React-Table you aren't notified that the page changed internally to 1 (0) if somebody filters the data. So you get stuck on page N even if there is not enough data available to display page N.
If you're not passing `page` to React-Table the page changes to 1 when you start filtering the data.

## What are the steps to reproduce the issue?
1. Go to https://codesandbox.io/s/817v7rlqvl
2. You are on page 4 of 556
2. Click on the button to go to next page
3. You are on page 5.
4. Write **z** in the filter under First name
5. You are on Page 4 of 3, instead of 1 of 3.
    * The onPageChange callback wasn't called
    * Internally react-table sets the page to 0 ([lifecycle.js](https://github.com/react-tools/react-table/blob/master/src/lifecycle.js#L102-L105)) , but the state overwrites the newly set property ([getResolvedState](https://github.com/react-tools/react-table/blob/master/src/methods.js#L6-L12)).

## Thanks for the library!

**Comment by gary-menzel** [comment]
I don't think this is a "bug" as such - possibly more confusion around what happens when you implement `onPageChange` and `onPage`. Basically you are taking over responsibility for page management at that point.  You would also have to implement `onFilteredChange` and check to see if you need to adjust the `page` as well.

ReactTable is not like a shrink-wrap table packages - it is more of a hackers table.  Once you start digging into replacing handlers and managing the internal state externally, you'll find you have to implement other handlers to keep everything working.

`onPageChange` is in the section about **Fully Controlled Component** which states:

> React Table by default works fantastically out of the box, but you can achieve even more control and customization if you choose to maintain the state yourself. It is very easy to do, even if you only want to manage parts of the state.

Some _parts_ depend on others.

If you take the `onPageChange` and `page` props out, then ReactTable itself properly manages the page and changes it back to "1 of...".

**Comment by DamianFekete** [comment]
@gary-menzel , thanks for your feedback.

I agree and thinking about it it makes no sense to call the callback, which is described as _Called when the page index is changed **by the user**_

The only issue may be that you're losing some default functionality without even knowing it by implementing some handlers or setting a prop :)
