### ISSUE TITLE
ReactTable in new window with React Portal

### ISSUE THREAD

**Issue by Pjata** [react-tools/react-table#811]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Hello!
I am trying out a new feature in React 16 called portal.
Based on this [article](https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202).
However, when i try to get ReactTable to work in the newly opened window it gets messy as you can see in the sandbox below.
Is there anyway i can make ReactTable work in a new window with portal?
It would be such a good feature for our users (popout the table to a new tab for double monitor setup).
Best regards,
Pjata
## Sandbox
https://codesandbox.io/s/84035j8168

## What are the steps to reproduce the issue?
1. Click the open button to open react table in new window portal-ed.

**Comment by gary-menzel** [comment]
Have you got the correct DOCTYPE in that popup window ?

https://github.com/react-tools/react-table/wiki/FAQ#my-reacttable-doesnt-seem-to-display-properly-on-browser-x---help

[When I hit OPEN it did not appear to have it when I opened the console - but I was not able to check the page source. Usually, those elongated buttons are because of that.]

**Comment by Pjata** [comment]
This only fixed the display issues, but the buttons are not working.
Refreshed sandbox:
https://codesandbox.io/s/84035j8168

**Comment by gary-menzel** [comment]
Well, there is no Javascript loaded to run the table.  All that seems to be there is the rendered table.  This would be an issue with how the portal is setting up the window.  Seems like there is CSS loaded - but no javascript to run anything.

**Comment by gary-menzel** [comment]
I think this issue is probably better discussed in a general React forum around the new feature as it is not really an issue with ReactTable.

**Comment by gary-menzel** [comment]
I think the problem here is the "new window" and not ReactPortal.  A new window is "new" in every way.  I has no HTML, no CSS, and no Javascript - you have to load that yourself.  That means you would have to load the whole React system and every supporting package that your page needed.

From what I just read about React Portal it is mainly used to break out of the main DOM line for things like popups, dialogs and modals (I don't think it was meant to be for opening a whole new window).

Maybe you need something more like this: 

https://rmariuzzo.github.io/react-new-window/

**Comment by Pjata** [comment]
I think I will ask around in about more general React forums.
Thank you for your help,  if i get any working solution I will post it here in this issue.

**Comment by gary-menzel** [comment]
Here is my take on it.  That article doesn't render a ReactComponent.  It renders normal HTML (the `<button>` is being converted by React into a normal button.  I think something as complex as a whole stateful component (like ReactTable) is not getting ported across properly.

Having said that, I could not even get a basic button to actually work (i.e. to do anything useful) in the new window.

**Comment by Pjata** [comment]
That seems to be the case. I hope I will get some clarifications about the limitations of this method by the guys at the react github.
