### ISSUE TITLE
SetState from Subcomponents

### ISSUE THREAD

**Issue by jalajrocking** [react-tools/react-table#820]
Hello, I am using react table v6.7.6. I want to know how do I update a state from subcomponents.

I want to make a state, set it at the time of subcomponent rendering and display the data like this

columns={this.state.col}

While setting a state from subcomponent its giving me a error of could not set state inside render.

How can I set a state in such a scenario?

**Comment by gary-menzel** [comment]
You should build your SubComponent as an actual Component and not try and manipulate the parent state from the SubComponent (it is considered as child).  React itself will not allow you to call `setState` in the `render` but an actual Component runs separately.

Otherwise, you should consider a central state handler like Redux or MobX.

**Comment by sourav2029** [comment]
@gary-menzel  how can i achieve this for the react-table ? Basically i want to open a form on click of a row of the table. When the form is saved i want to close the form component update the row to reflect the user input and make a call to update the db as well.

**Comment by gary-menzel** [comment]
@sourav2029 Sorry - it is not a simple answer and would require me to build something (and I don't have the time to do that).  You should try to mock something up in codesandbox.io or stackblitz.com to understand how the mechanism of SubComponent works (copy the example). Then if you have something you don't understand you can post a question on the #react-table Slack channel (badge at the top of the README in the doco).  Thanks.
