### ISSUE TITLE
Text input filtering on a controlled component is difficult to edit middle text

### ISSUE THREAD

**Issue by nickguimond** [react-tools/react-table#838]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Text input filtering on a controlled component, when you try to edit the middle area of the text the cursor jumps to the end after the first char. 
Example: https://react-table.js.org/#/story/controlled-component
Type a word "brother"  and move text cursor to after the b..  then delete the r and notice the text cursor jump to the end.

**Comment by gary-menzel** [comment]
You really need to implement a specific component to do the editing for your own use-cases.  Using the example in the docs for production is not recommended.  That is because it uses the SAME state as ReactTable and therefore controlled changes to the `input` will cause ReactTable to refresh as well as the content in the `input`.  If you make a specific component with it's own state and then handle a callback when the data is ready to process then this issue will not happen.
