### ISSUE TITLE
"No rows found" shown underneath "Loading..." when loading is true and data is undefined

### ISSUE THREAD

**Issue by mrubin** [react-tools/react-table#860]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
My component fetches data from the server and has a `loading` prop (which is set to `true` while we're fetching data and changes to `false` once the data is available). I want to use this existing `loading` prop to set the correct loading state on ReactTable by doing the below:

```
let tableData = loading ? undefined : myData

<ReactTable
  loading={loading}
  data={tableData}
  ...
```

What I see is that when the "Loading..." indicator is shown, underneath it I also see "No rows found" even though I am setting `data={undefined}`. This seems like a bug. When the table is in the loading state, "No rows found" should not be shown.

I also tried not setting the `data` prop at all, but there was no change in behavior:

```
if (loading) {
  <ReactTable
    loading={true}
    ...
} else {
  <ReactTable
    data={myData}
    ...
}
```

maxrosecollins from the Slack channel said they see the same behavior as well.

**Comment by saichandesh** [comment]
Hi @mrubin , I have created a PR ( [https://github.com/react-tools/react-table/pull/861](https://github.com/react-tools/react-table/pull/861) ) to fix this issue. Go through it and let me know if there are any comments on it.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Comment by Billy-** [comment]
@tannerlinsley this is definitely still an issue, a PR was made (#861) but has been closed by @gary-menzel as he doesn't agree that it is an issue. We (the community) are unanimous in our stipulation that this is, in fact, an issue.

The discussion should have been had here, rather than the PR (PR's are for discussing the code, we should have discussed the issue here), but if you could take a look at the conversation over there (#861) and weigh in, I'm sure we would all very much appreciate that.

Kindest regards,
