### ISSUE TITLE
In mobile devices, resizing table header columns also drags the table

### ISSUE THREAD

**Issue by derrick-p** [react-tools/react-table#866]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
In mobile devices or touch screens, resizing table header columns also drags the table if there is responsive horizontal scrolling.

This causes the column you are dragging to move away from your finger.  It's a bit wonky.

Perhaps disable 'touchmove' when a column is being resized?

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Just need to add table columns or increase their width so that the table has horizontal scrolling.

## What are the steps to reproduce the issue?
1. Create a react table with responsive horizontal scrolling
2. Open the page with the table in a mobile device
3. Drag to resize the columns

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
