### ISSUE TITLE
Pivoting expansion rows values

### ISSUE THREAD

**Issue by tigran-sedrakyan** [react-tools/react-table#882]
Hey guys, and thanks for an awesome package!

I'm experiencing issues with pivoting. When I expand a pivoted row, value of that row corresponding to the pivoted column is not being shown, and an empty cell is being rendered for every row in the expansion (see the picture attached). Is there a way to make the pivot value visible in every row in the expansion?

Thanks in advance!
![screenshot_20180330_172643](https://user-images.githubusercontent.com/18465490/38139480-9b0a606e-3440-11e8-9128-0f0d89a50dee.png)

**Comment by pnaw94** [comment]
I've recently experienced the same problem. This is probably due to this code fragment: https://github.com/react-tools/react-table/blob/8bd3daafcb2c311fa959f5d9440ee275be2841fe/src/index.js#L653-L681
(especially L680)

If I understand this correctly, it means that the cells under pivot cell are automatically hidden and you can't configure that. A workaround for this is overriding Cell property of the column and identify a property that is different for parent and child rows, and then for that case set `pivoted = false` for the cell. This is a bit hacky, but will work for now.

Example:
`
Cell: cellData => {
          if (cellData.original) {
            cellData.pivoted = false;
            return cellData.original.otherValue;
          } else {
            return cellData.value;
          }
        }
`

**Comment by tigran-sedrakyan** [comment]
Thanks, works just fine!

**Comment by gary-menzel** [comment]
I strongly recommend you test this in as many possible scenarios as you can before using it in Production.  The solution is changing internal values generated by ReactTable which *may* be required for other functionality.

**Comment by EmaSuriano** [comment]
Hello, I suggest using TreeTableHOC. It's incredibly easy to set up
