### ISSUE TITLE
Add Bootstrap Dropdown Menu 

### ISSUE THREAD

**Issue by caktoy** [react-tools/react-table#893]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
I want to add a dropdown button from bootstrap on each row, but when the dropdown button is clicked, the dropdown menu does not appear because the row is hidden under it. Is there a solution to solve it?

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/xlzl0v2o5p

## What are the steps to reproduce the issue?
1. Add Bootstrap CSS dependencies, I use reactstrap (https://reactstrap.github.io/) in this case to avoid jquery needs.
2. Render each row with dropdown component

**Comment by gary-menzel** [comment]
You will need to modify the CSS on the cell as it is designed to contain the content within the cell - or use a mechanism that attaches the dropdown to the `body` rather than inside the cell.  It's going to be different depending on your use case and what CSS is already being provided by your Bootstrap classes.
