### ISSUE TITLE
getTdProps onClick handleOriginal not allowing expandable

### ISSUE THREAD

**Issue by DaKaZ** [react-tools/react-table#900]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
BUG: we have a form that is rendered above the table that allows adding/editing of data that is displayed in the table.  When a row is clicked, we set the component's local state with the information from that row.  We also have a subComponent which is displayed when the row is expanded.  When we have the local `this.setState` we do NOT get the expansion of the react table.  However, if I delay the setState with a timeout, everything works.

```
        <ReactTable
          data={data}
          columns={columns}
          className="-striped -highlight"
          defaultPageSize={10}
          freezeWhenExpanded={false}
          collapseOnDataChange={false}
          filterable
          filtered={this.state.filtered}
          onFilteredChange={(filtered) => { this.setState({ filtered }); }}
          getTdProps={this._selectProject}
          SubComponent={(row) => (
            <Releases project={row.original} addRelease={this.props.addRelease} />
          )}
        />
```

```
  _selectProject = (state, rowInfo) => ({
    onClick: (e, handleOriginal) => {
      if (handleOriginal) {
        handleOriginal();
      }
      // React-table won't expand without the delay, hmmmmm
      setTimeout(() => {
        this.setState({
          id: rowInfo.original.id,
          name: rowInfo.original.name,
          account_ids: rowInfo.original.accounts
          && rowInfo.original.accounts.map((a) => a.id)
        });
      }, 50);
    }
  });
```

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/jpow5j13mw

## What are the steps to reproduce the issue?
Using the sandbox above...
Expand one of the rows in the table.  We should see the simple label on top update AND the sub component expanded.

**Comment by gary-menzel** [comment]
The codesandbox you posted had `getTrProps` instead of `getTdProps` but did not have the `setState` call in it. So, the `onClick` was not getting a proper `handleOriginal` (as that is not passed in the `getTrProps`.

But, obviously, that is not the issue you were referring to - but the example posted doesn't trigger the issue.

**Comment by DaKaZ** [comment]
@gary-menzel sorry about that.  Please see the sandbox now as it correctly has getTdProps and the setState uncommented.

**Comment by gary-menzel** [comment]
You have a race condition with `setState` and `handleOriginal`.

When you call `setState` it is triggering off an asynchronous change to the state of your component (and hence the state passed in to ReactTable - causing ReactTable to render again due to the state change).  So what is actually happening is `handleOriginal` is getting called first (before React processes your `setState`) and then the `setState` is triggering.

If you move the `handleOriginal` code into the a `setState` callback, you can avoid the `setTimeout` - something similar to the following:

```
      this.setState({ firstName: rowInfo.original.firstName },() => {
        if (handleOriginal) {
          handleOriginal();
        }
      });
```
This ensures your `handleOriginal` call will not be trigger until React itself has finished the whole update cycle.

I'll close this for now.  If you have any further implementation questions please head over to the react-table Slack channel (badge at the top of the README in the doco site).  Thanks.

**Comment by DaKaZ** [comment]
Brilliant. Thanks!
