### ISSUE TITLE
What are versions 6.7.6 and 6.8.0?

### ISSUE THREAD

**Issue by tusbar** [react-tools/react-table#914]
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
Version `6.8.0` is released on [npm](https://www.npmjs.com/package/react-table), there is no mention of it in this repository, package.json is at `6.7.6`, the last tag is `6.7.6` but changelog only mentions `6.7.5`.

`6.8.0` was released 2 months ago on npm, so I’m wondering what it’s about and what changed.

---

cc @gary-menzel

**Comment by gary-menzel** [comment]
I don't have an answer for you.  There were a bunch of PRs that were pushed through by @tannerlinsley and I am aware that there is some background work being done on a new version.

I would suggest that 6.7.6 is the STABLE version at this point - it is still the one I am using for PRODUCTION work.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
