### ISSUE TITLE
Editing "next" and "prev" onClick functionality

### ISSUE THREAD

**Issue by younusmahmood** [react-tools/react-table#917]
How do I access those buttons to add my own custom onClick handlers? Even when using the onPageChange method it doesn't do anything when next or previous are clicked

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
