### ISSUE TITLE
AutoFit table

### ISSUE THREAD

**Issue by marina8915** [react-tools/react-table#921]
version of React-Table ^6.8.0
How can I create an AutoFit table when height and width are adjusted to the data?

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
