### ISSUE TITLE
Forcing fetchData on componentDidUpdate

### ISSUE THREAD

**Issue by gabouy** [react-tools/react-table#924]
Hi,

I'm using version 6.8.2 of react-table.

I'm trying to filter the contents displayed in the table based on a query param, matched by the router to a property.

The function used to fetch data from the server uses this property. The first time the component is rendered it displays the data as expected, filtered according to the received param. 

However, if the url changes, the component updates, the prop is updated, render is invoked, but onFetchData is not being triggered. 

What should I do? What'd be the best way to model this using react-table?

thanks!

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
