### ISSUE TITLE
Links in the main documentation are 404s

### ISSUE THREAD

**Issue by ubaidseth** [react-tools/react-table#929]
## What version of React-Table are you using?

Current version. 6.8.1

## What bug are you experiencing, or what feature are you proposing?

readme --> 
https://github.com/react-tools/react-table/blob/master/stories/ServerSide.js

## What are the steps to reproduce the issue?

1.  Go to https://github.com/react-tools/react-table
2.  Click on the "server side" example url.

**Comment by gary-menzel** [comment]
The documentation is the lowest priority in terms of change control.  That "server side" example no longer exists (so it would only be to remove the link).

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
