### ISSUE TITLE
Potential infinite loop: exceeded 10001 iterations.

### ISSUE THREAD

**Issue by esetnik** [react-tools/react-table#932]
https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components

```
Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.
range
/Utils.js:7:32
   4 | 
   5 | const range = len => {
   6 |   const arr = [];
>  7 |   for (let i = 0; i < len; i++) {
     |                                ^
   8 |     arr.push(i);
   9 |   }
  10 |   return arr;
```

**Comment by gary-menzel** [comment]
This has already been reported several times.  This is an issue with changes in codesandbox that has not made it far enough up the list yet to resolve.  You can solve it by forking the codesandbox and then setting the loop checking controls in the configuration for your fork of the sandbox.

**Comment by radi-cho** [comment]
Hello!
I experienced the same error, opened issue and then realized that it's duplicate.
However...
@gary-menzel - Yeah, it is issue with the recent codesandbox changes. But you can fix it by adding sandbox.config.json and setting the `infiniteLoopProtection` to `false`.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
