### ISSUE TITLE
How to get the data of the "fake" row expanded from onExpandedChange

### ISSUE THREAD

**Issue by sealightPT** [react-tools/react-table#935]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
When using react-table with pivot and expanding rows the index provided on onExpandedChange is a view index. 
This means we don't know what was the real data expanded.
How can we have access to the data on onExpandedChange(newExpanded, index, event) ?
The other properties provided by the event don't seem to help.

PS: We would like to use this to control which rows should be allowed to expand and which shouldn't. For instance: A parent row which has a single children (which will be identical to the parent "fake" row) shouldn't be expandable.

**Comment by gary-menzel** [comment]
You are absolutely correct in what you are saying - you don't know the index of the underly row that the pivot row comes from.  This is just how it is built and would require a rewrite of the pivot mechanism to do otherwise.

You could look at adding a `ref` to your ReactTable instance and walking the resolved data tree but if this is a major requirement for you then it may be better to consider a different package because it just currently isn't set up to work the way you have described.

**Comment by sealightPT** [comment]
Is it possible to have a ref on the row with some sort of id tied to to view index so that we can find the underlying data row when on onExpandedChange ?
Otherwise the index received is not of much help.
And what are the newExpanded and event arguments? I can't seem to get nothing from them.

**Comment by gary-menzel** [comment]
There are no `refs` on the rows. As I said previously - nothing wrong with your concept but it is just not possible in the way that ReactTable is built.

* `newExpanded` is the complete structure of expanded rows using the `viewIndex`
* `index` is actually a path made up of the `viewIndex`
* `event` is the click event (although that may not be usable due to the pooling of synthetic events by React itself

**Comment by gary-menzel** [comment]
As I also said earlier, you can put a `ref` on ReactTable and then call `getResolvedState()` (as per info in the wiki FAQ here) and work everything out from that.  You can translate the `viewIndex` into a "row" of sorts by looking at the `page` and the `pageSize` and then picking out the start in the `sortedData` array which would be `viewIndex` 0 and then offsetting from there.  For a pivoted table that will be the top level "fake" row and it contains the subrows.  The `expanded` structure mimics the nesting of that with the `viewIndex` numbers.

The reason it is built that way is for the purposes of rendering and keeping it all light weight.

It can all be done - you can access it all - but, again, as I said, you may be better off looking at a different component that works closer to your modelling.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
