### ISSUE TITLE
Not using td, tr, etc

### ISSUE THREAD

**Issue by SelaO** [react-tools/react-table#938]
Why this library uses divs instead of tds, trs, etc? Is there a way to force it to use proper table tags? 

Will "overriding" also override the html tags? 

![image](https://user-images.githubusercontent.com/21977571/39420135-d180aade-4c6b-11e8-908f-652319c16a3e.png)

**Comment by gary-menzel** [comment]
It uses `div` because the table model is broken in HTML.

You can override most of the components but, if you want to built a table using `tr` and `td` then you are better off looking for a different package (as ReactTable was specifically designed to NOT use the normal HTML elements).

**Comment by SelaO** [comment]
What do you mean the table model is broken? Do you have a link to back this up?

**Comment by gary-menzel** [comment]
Like I said - if you want to use the table model... go right ahead. If you aren't aware of the problems that the table model causes then you probably have simple requirements and probably don't need ReactTable. 

ReactTable uses `divs` because they are easier to control to meet the authors original requirements as laid out in the original article he wrote on why he built it.

https://medium.com/@tannerlinsley/why-i-wrote-react-table-and-the-problems-it-has-solved-for-nozzle-others-445c4e93d4a8

As this is not actually an issue with ReactTable (a bug or a feature request) I'll be closing this now.
