### ISSUE TITLE
How to change the style of row by clicking that row?

### ISSUE THREAD

**Issue by tesicg** [react-tools/react-table#945]
For example, I would like to highlight the row that I `clicked` (selected).

`<ReactTable
    getTrProps={(state, rowInfo, column) => {
        return {
            onClick: ????
        };
    }}
    ...
/>
`
How to do it?

**Comment by gary-menzel** [comment]
I responded to you in the #react-table slack channel with an example in codesandbox

**Comment by tesicg** [comment]
Thank you. I'll take a look.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
