### ISSUE TITLE
dynamically getting data when the user changes a page

### ISSUE THREAD

**Issue by juancafe4** [react-tools/react-table#949]
Hello,
I was wondering if you can load new data every time you change a page. I have a REST API where I only get certain number of data ex: 1 to 10 the 11 to 20 and so on. so there is a way to change data when user changes a page?

**Comment by gary-menzel** [comment]
Look at `onFetchData` and set the `manual` flag on the component.  Look at the section in the doco call "Server-side Data"

**Comment by juancafe4** [comment]
thanks I ll stick with bootstrap-table then

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
