### ISSUE TITLE
Save and restore state?

### ISSUE THREAD

**Issue by amivag** [react-tools/react-table#954]
I would like to save the react-table state (e.g. page number, rows per page etc...) in an objct variable, when the component is about to unmount, and restore it when it mounts again. It's a simple technique to allow components remember their state/settings when they are unmounted (unless somebody has a better idea).

How can I do this with react-table? Any example?

Thanks

**Comment by gary-menzel** [comment]
Simply provided handlers for each of the things you want to save and then write your handler.

The only things worth keeping are:

- onPageChange
- onPageSizeChange
- onFilteredChange
- onSortedChange
- onResizeChange

Everything else, your `data', `columns`, `pivotBy` - etc. - are being supplied as props in the first place (so they are already known).

Then, push them back into your `state` when you need to restore them.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
