### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by gadi246** [react-tools/react-table#956]
## What version of React-Table are you using?
6.8.2

## What bug are you experiencing, or what feature are you proposing?
I render React-Table with TBody custom component + no pagination. when data refreshes and the data array is getting larger with added rows to the old ones React-Table renders the whole row list data array.
The main indication is that the scroll bar of the tbody jumps back up on data refresh. 

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

Then paste a link to your newly forked codesandbox here...
https://codesandbox.io/s/00y5yo7xxv
## What are the steps to reproduce the issue?

1.  list the steps
2.  to reproduce
3.  the issue

**Comment by gary-menzel** [comment]
ReactTable is NOT optimized for a vertical scroll situation.  It is a PAGE-BASED table - not a scrollable one. I'd suggest NOT using vertical scrolling or finding a different package.

**Comment by gadi246** [comment]
Got it, Thanks!

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
