### ISSUE TITLE
Custom props addded through 'getHeaderProps' not available in 'Header' callback

### ISSUE THREAD

**Issue by fgaleano** [react-tools/react-table#962]
## What version of React-Table are you using?
6.7.4
## What bug are you experiencing, or what feature are you proposing?

I have some flags stored at the Redux level that I need to expose to React-Table headers and cells. For cells I'm using the `getProps` callback and attaching my flags which in turn are being applied to ReactTable as top level props. This works ok but it fails in the headers. `getPropsHeader` works but the props I add are not then available in the Header renderer.

Our columns settings are big and complicated so they are in a separate library file where there is no Redux to pass the props directly to the callbacks, like I've seen in most examples. Is there another way to pass down these top level props on <ReactTable /> to Header callbacks as well?

https://codesandbox.io/s/r788rpnjqm

## What are the steps to reproduce the issue?

1.  Return new props using 'getHeaderProps'
2.  Access the `props` parameter in the `Header` callback and confirm the new props are not present. This same method works for `getProps` in the `Cell` callback.

**Comment by gary-menzel** [comment]
I understand what you are saying, but, unless your columns are changing dynamically (and it just makes it more complex) you can decorate your columns inside you wrapping component before the first render (either in the `constructor` or one of the React lifecycle methods).  That way, you can add in-scope functionality when the component is initialised.  The case where the columns may change outside requires you to either use something like the new React context mechanism or the old lifecycle methods for changing props).

I hope this makes sense.  There is unlikely to be any change to the existing version of ReactTable as that would require a code-wide change.  It may be considered for the next major re-write.

@tannerlinsley might want to review this request.

**Comment by fgaleano** [comment]
The columns don’t change dynamically so that’s not a problem. At first render is enough.

So what you’re suggesting is to intercept the columns settings in the container component and mutate them BEFORE passing them to React Table? How, exactly? Are there any callbacks I can use or would it be overriding the ‘Header’ callback that was set in the original object? I’m not sure I follow so hopefully you can add more details or an example.

Ideally I’d be able to pass these props to the renderer callbacks and just use them when their called. It may not be possible then. I just don’t want to mess up the container component with logic that stricyly belong there the columns. Perhaps I need to wrap my columns into an high order function that receives the Redux state and then outputs the columns object.

Thank you very much for your time and this library.

**Comment by gary-menzel** [comment]
What you have described is definitely what I meant - I don't have a generic example (everything is wrapped up in my code).  However, the `selectTableHOC` example augments the columns on the way in to ReactTable - so that might provide some hints.

Another possibility is to pass a "getColumns" function as a prop and then call that back and pass in the "this" of the wrapping component so you can get the context you need that way.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
