### ISSUE TITLE
Apply saved sort after refresh not working

### ISSUE THREAD

**Issue by ivanisko** [react-tools/react-table#964]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I'm using server-side data rendering and after change of sort. I saved sort to localStorage and state of React-table to tableState var, every time when fetchData is called. I also check if my component state variable sort is not empty and then set react table sorted variable.
In componentDidMount I check the localStorage and save to component state as sort variable and then call fetchData with tableState var.

My problem is when i refresh page sort of data is in right order like last time, but in header I don't have visual information about sort. See picture.

<img width="235" alt="screen shot 2018-05-11 at 15 49 22" src="https://user-images.githubusercontent.com/1854118/39927569-f5fff0e8-5532-11e8-8d2f-d65eb82bd80d.png">

Can you look a help me where can be problem. Thank you

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

https://codesandbox.io/s/4roqr76mmw

## What are the steps to reproduce the issue?

1.  sort some column 
2.  refresh page

**Comment by gary-menzel** [comment]
I see what you are trying to do.  However, you are going to run into a race condition and end up with an infinite loop.  There really is no way to use `onFetchData` and be able to set a filter/sort externally - because setting it using `props` will cause `onFetchData` to trigger again, which will cause the props to be updated, which will cause 'onFetchData` to be triggered again.....

You have to ask yourself if you really need to call `onFetchData` (it is not something I ever find I need to do - but, for some reason, everyone wants to use it).  I think it is related to NOT thinking in old ways and thinking more in "React".

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
