### ISSUE TITLE
Feature Request : Moving Columns and Infinite scroll

### ISSUE THREAD

**Issue by pavanshinde47** [react-tools/react-table#966]
Hi All,

I tried looking for but didn't find anything related to moving columns and infinite scroll. Can this be implemented?

**Comment by gary-menzel** [comment]
Firstly, ReactTable is NOT a scrollable table - it is page-based.  You can implement "infinite" pages of sorts using the `onFetchData` mechanism and setting the `pages` to `Infinity`.

Moving columns won't be done with drag and drop in the current version - they may not even make a future rewrite.  The reason being that doing so requires additional libraries (or purpose built implementations) and ReactTable is deliberately agnostic (as per the authors original Medium post).  Currently, people implement moving columns external to ReactTable (using some type of drag and drop list of columns - with the ability to also hide/show columns).

If those features are important for your use-case then you should look for a different table package.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
