### ISSUE TITLE
Can I build a two dimensional table?

### ISSUE THREAD

**Issue by AlexKutkanych** [react-tools/react-table#974]
I am struggling to build a two dimensional table. The data has depend not only on columns, but on rows also (see attachment). Can I do this with your library?

Or can I switch rows and columns? So I set data depending on row value.

![image](https://user-images.githubusercontent.com/22956226/40188914-b667a392-5a03-11e8-83af-82d8dfc71211.png)

**Comment by gary-menzel** [comment]
It's just data - your first column would just have the text in it you want to display with an empty header.

If you mean that the first column is like a frozen column and you are going to add more data columns to the right and you want them to be scrollable while the left side stays fixed...... No - not possible with the current version of React Table.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
