### ISSUE TITLE
Feature Request: Multiple filter rows

### ISSUE THREAD

**Issue by pwhipp** [react-tools/react-table#981]
Version 6.7.6

The filter row is great for conjunctive filtering (each row must meet each column filter pattern).

However, we've had user requests for disjunctive filtering. For example where the status column equals 'needs_attention' and the role column equals 'primary' or 'cache'.

An elegant way to handle this is to allow multiple filter rows where each data row can match any one (or more than one) filter row.

I'll aim to revisit this with a fork or HOC after our next release (June) if I can find time but thought I'd add it here in case anyone else needs something similar.

**Comment by tannerlinsley** [comment]
Closing as part of our long-overdue issue cleanup. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
