### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by toddpiltingsrud** [react-tools/react-table#992]
Nice component! 

Consider adding accessibility features, especially since this component uses div elements instead of the more self-descriptive table elements.

https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#grid

Here's a presentation I recently attended that put this topic front and center in my mind:

https://youtu.be/txdDJNgqVlw?t=1821

**Comment by tannerlinsley** [comment]
I welcome any and all PR's to implement this :)

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
