### ISSUE TITLE
[feature request] Alternative ways to trigger multisort

### ISSUE THREAD

**Issue by nevnein** [react-tools/react-table#995]
First of all, thank you for your work, this component is great!

## What bug are you experiencing, or what feature are you proposing?

It would be nice to have an alternative way to trigger multisort on click.
Right now the shift click is totally fine on desktop but the feature is lost/hard to use on mobile devices like tablets. 
I'm thinking of some sort of prop value that toggles the click behaviour on ThComponents, so that you can (optionally) control it with, dunno, a checkbox or whatever.

Thank you for your time!

**Comment by tannerlinsley** [comment]
Great point. We'll have to play with a few ideas on this.

**Comment by capaj** [comment]
maybe have like a `+` button appear on the other columns once you select one column?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
